// GENERATED by scripts/gen-readme.mjs from registry/v1/stable/registry.json — do not edit.
// Run `pnpm gen:readme` to regenerate; `pnpm gate:readme` checks for drift.

export interface GeneratedWallet {
  id: string;
  name: string;
  networks: string[];
  capabilities: {
    signMessage: boolean;
    signTransaction: boolean;
    submitTransaction: boolean;
    transactionStatus: boolean;
    switchNetwork: boolean;
    multiParty: boolean;
  };
  /** True when the adapter is opt-in (requires explicit config/registration). */
  optIn: boolean;
  adapter: string;
}

export const GENERATED_WALLETS: GeneratedWallet[] = [
  {
    id: 'console',
    name: "Console Wallet",
    networks: ['devnet', 'testnet', 'mainnet'],
    capabilities: { signMessage: true, signTransaction: true, submitTransaction: true, transactionStatus: true, switchNetwork: false, multiParty: false },
    optIn: false,
    adapter: "@partylayer/adapter-console",
  },
  {
    id: 'loop',
    name: "5N Loop",
    networks: ['devnet', 'testnet', 'mainnet'],
    capabilities: { signMessage: true, signTransaction: false, submitTransaction: true, transactionStatus: true, switchNetwork: false, multiParty: false },
    optIn: false,
    adapter: "@partylayer/adapter-loop",
  },
  {
    id: 'cantor8',
    name: "Cantor8",
    networks: ['devnet', 'testnet', 'mainnet'],
    capabilities: { signMessage: true, signTransaction: true, submitTransaction: false, transactionStatus: false, switchNetwork: false, multiParty: false },
    optIn: false,
    adapter: "@partylayer/adapter-cantor8",
  },
  {
    id: 'bron',
    name: "Bron",
    networks: ['devnet', 'testnet', 'mainnet'],
    capabilities: { signMessage: true, signTransaction: true, submitTransaction: false, transactionStatus: false, switchNetwork: false, multiParty: false },
    optIn: true,
    adapter: "@partylayer/adapter-bron",
  },
  {
    id: 'nightly',
    name: "Nightly",
    networks: ['devnet', 'testnet', 'mainnet'],
    capabilities: { signMessage: true, signTransaction: false, submitTransaction: true, transactionStatus: false, switchNetwork: false, multiParty: false },
    optIn: false,
    adapter: "@partylayer/adapter-nightly",
  },
  {
    id: 'send',
    name: "Send",
    networks: ['mainnet'],
    capabilities: { signMessage: true, signTransaction: false, submitTransaction: true, transactionStatus: true, switchNetwork: false, multiParty: false },
    optIn: false,
    adapter: "@partylayer/adapter-send",
  },
  {
    id: 'walley',
    name: "Walley",
    networks: ['mainnet', 'testnet', 'devnet'],
    capabilities: { signMessage: true, signTransaction: false, submitTransaction: true, transactionStatus: true, switchNetwork: false, multiParty: false },
    optIn: false,
    adapter: "@k2flabs/walley-dapp-sdk",
  },
  {
    id: 'walletconnect',
    name: "WalletConnect",
    networks: ['devnet', 'testnet', 'mainnet'],
    capabilities: { signMessage: true, signTransaction: false, submitTransaction: true, transactionStatus: false, switchNetwork: false, multiParty: false },
    optIn: true,
    adapter: "@partylayer/adapter-walletconnect",
  },
];
