// API SURFACE SNAPSHOT — @partylayer/adapter-cantor8
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class Cantor8Adapter implements WalletAdapter { readonly walletId: _partylayer_core.WalletId; readonly name = "Cantor8"; private readonly config; private provider; constructor(config?: Cantor8AdapterConfig); getCapabilities(): CapabilityKey[]; private mapNetwork; detectInstalled(): Promise<AdapterDetectResult>; connect(ctx: AdapterContext, _opts?: { timeoutMs?: number; }): Promise<AdapterConnectResult>; disconnect(_ctx: AdapterContext, _session: Session): Promise<void>; signMessage(_ctx: AdapterContext, _session: Session, _params: SignMessageParams): Promise<SignedMessage>; submitTransaction(_ctx: AdapterContext, _session: Session, params: SubmitTransactionParams): Promise<TxReceipt>; on(event: AdapterEventName, handler: (payload: unknown) => void): () => void; }
export { Cantor8Adapter, type Cantor8AdapterConfig, type Cantor8SubmitPayload };
import * as _partylayer_core from '@partylayer/core';
import { WalletAdapter, CapabilityKey, AdapterDetectResult, AdapterContext, AdapterConnectResult, Session, SignMessageParams, SignedMessage, SubmitTransactionParams, TxReceipt, AdapterEventName } from '@partylayer/core';
interface Cantor8AdapterConfig { dappUrl?: string; detectTimeoutMs?: number; }
interface Cantor8SubmitPayload { note?: string; partyId: string; commandId: string; commandsJson: string; disclosedContracts?: string; }
