// API SURFACE SNAPSHOT — @partylayer/adapter-bron
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import * as _partylayer_core from '@partylayer/core';
import {
  WalletAdapter,
  CapabilityKey,
  AdapterDetectResult,
  AdapterContext,
  AdapterConnectResult,
  SignMessageParams,
  SignTransactionParams,
  LedgerApiParams,
  LedgerApiResult,
} from '@partylayer/core';

/**
 * Bron OAuth2 Authentication Client
 *
 * Handles OAuth2 flows for Bron enterprise wallet.
 *
 * References:
 * - Bron developer portal: https://developer.bron.org/
 * - Bron ecosystem: https://www.canton.network/ecosystem/bron-wallet
 */

/**
 * OAuth2 configuration
 */
interface BronAuthConfig {
  /** Authorization server URL */
  authorizationUrl: string;
  /** Token endpoint URL */
  tokenUrl: string;
  /** Client ID */
  clientId: string;
  /** Client secret (for server-side flows) */
  clientSecret?: string;
  /** Redirect URI */
  redirectUri: string;
  /** Scopes */
  scopes?: string[];
  /** Use PKCE (recommended for browser) */
  usePKCE?: boolean;
}

/**
 * Bron API Client
 *
 * Typed client for Bron enterprise wallet API endpoints.
 *
 * References:
 * - Bron developer portal: https://developer.bron.org/
 */

/**
 * Bron API configuration
 */
interface BronApiConfig {
  /** Base API URL */
  baseUrl: string;
  /** Access token getter */
  getAccessToken: () => Promise<string | null>;
}

/**
 * Bron adapter configuration
 */
interface BronAdapterConfig {
  /** OAuth2 configuration */
  auth: BronAuthConfig;
  /** API configuration */
  api: BronApiConfig;
  /** Use mock API in development */
  useMockApi?: boolean;
}
/**
 * Bron Wallet Adapter
 */
declare class BronAdapter implements WalletAdapter {
  readonly walletId: _partylayer_core.WalletId;
  readonly name = 'Bron';
  private authClient;
  private apiClient;
  constructor(config: BronAdapterConfig);
  /**
   * Create mock API client for development
   */
  private createMockApiClient;
  getCapabilities(): CapabilityKey[];
  detectInstalled(): Promise<AdapterDetectResult>;
  connect(
    ctx: AdapterContext,
    _opts?: {
      timeoutMs?: number;
      requiredCapabilities?: CapabilityKey[];
    }
  ): Promise<AdapterConnectResult>;
  disconnect(_ctx: AdapterContext, _session: _partylayer_core.Session): Promise<void>;
  restore(
    _ctx: AdapterContext,
    persisted: _partylayer_core.PersistedSession
  ): Promise<_partylayer_core.Session | null>;
  signMessage(
    _ctx: AdapterContext,
    session: _partylayer_core.Session,
    params: SignMessageParams
  ): Promise<_partylayer_core.SignedMessage>;
  signTransaction(
    _ctx: AdapterContext,
    session: _partylayer_core.Session,
    params: SignTransactionParams
  ): Promise<_partylayer_core.SignedTransaction>;
  /**
   * Proxy a Canton Ledger API request through the Bron enterprise API.
   *
   * Bron acts as an authenticated HTTP proxy — it forwards the request
   * to the Canton Ledger API using the enterprise session credentials.
   */
  ledgerApi(
    ctx: AdapterContext,
    session: _partylayer_core.Session,
    params: LedgerApiParams
  ): Promise<LedgerApiResult>;
}

export { BronAdapter, type BronAdapterConfig, type BronApiConfig, type BronAuthConfig };
