// API SURFACE SNAPSHOT — @partylayer/react-native
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare function createAsyncStorage(asyncStorage?: RNAsyncStorage): SessionStorage;
declare function createAsyncStorageAdapter(asyncStorage?: RNAsyncStorage): StorageAdapter;
declare function createReactNativeClient(config: ReactNativeClientConfig): PartyLayerClient;
declare function createReactNativeDeepLinkPlatform(linking?: RNLinking): DeepLinkPlatform;
declare function useConnect(client: PartyLayerClient): UseConnectResult;
declare function useWallets(client: PartyLayerClient, parameters?: UseWalletsParameters): UseWalletsResult;
export { A as AccentOverrides, a as AccentPreset, D as DEFAULT_BORDER_RADIUS, I as IconFormat, P as PartyLayerTheme, R as REM_BASE_PX, b as ReactNativeTheme, T as ThemeFamily, c as accentPresets, d as applyAccent, e as deriveIconFormat, p as parseBorderRadius, t as themes, f as toReactNativeTheme, g as toThemeTokens, w as walletIconInfo } from './icons-DdH3oA7q.js';
export { type ConnectStatus, type RNAsyncStorage, type RNLinking, type ReactNativeClientConfig, type UseConnectResult, type UseWalletsParameters, type UseWalletsResult, WalletIconInfo, createAsyncStorage, createAsyncStorageAdapter, createReactNativeClient, createReactNativeDeepLinkPlatform, useConnect, useWallets };
import { DeepLinkPlatform, StorageAdapter } from '@partylayer/core';
import { PartyLayerConfig, PartyLayerClient, WalletFilter, WalletInfo, ConnectOptions, Session } from '@partylayer/sdk';
import { SessionStorage } from '@partylayer/session';
import { W as WalletIconInfo } from './icons-DdH3oA7q.js';
interface RNAsyncStorage { getItem(key: string): Promise<string | null>; setItem(key: string, value: string): Promise<void>; removeItem(key: string): Promise<void>; clear(): Promise<void>; }
interface RNLinking { openURL(url: string): Promise<unknown>; addEventListener(type: 'url', handler: (event: { url: string; }) => void): { remove(): void; }; getInitialURL(): Promise<string | null>; }
interface ReactNativeClientConfig extends PartyLayerConfig { asyncStorage?: RNAsyncStorage; }
interface UseConnectResult { connect: (options?: ConnectOptions) => Promise<Session>; disconnect: () => Promise<void>; session: Session | null; status: ConnectStatus; isConnecting: boolean; isConnected: boolean; error: Error | null; }
interface UseWalletsParameters { filter?: WalletFilter; }
interface UseWalletsResult { wallets: WalletInfo[] | undefined; walletIcons: WalletIconInfo[]; isLoading: boolean; isSuccess: boolean; isError: boolean; error: Error | null; refetch: () => void; }
type ConnectStatus = 'idle' | 'connecting' | 'connected' | 'error';
