// API SURFACE SNAPSHOT — @partylayer/adapter-walley
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import * as _partylayer_core from '@partylayer/core';
import {
  WalletAdapter,
  CapabilityKey,
  AdapterDetectResult,
  AdapterContext,
  PartyId,
  AdapterConnectResult,
  Session,
  PersistedSession,
  SignMessageParams,
  SignedMessage,
  SignTransactionParams,
  SignedTransaction,
  SubmitTransactionParams,
  TxReceipt,
  LedgerApiParams,
  LedgerApiResult,
  WalletNotInstalledError,
  TransportError,
  NetworkId,
} from '@partylayer/core';

interface WalleyAdapterConfig {
  /**
   * Override the Walley host. By default the adapter targets the hosted Walley
   * wallet for the active network; set this only to point at a self-hosted one.
   */
  host?: string;
}
declare class WalleyAdapter implements WalletAdapter {
  readonly walletId: _partylayer_core.WalletId;
  readonly name = 'Walley';
  private readonly hostOverride?;
  constructor(config?: WalleyAdapterConfig);
  getCapabilities(): CapabilityKey[];
  detectInstalled(): Promise<AdapterDetectResult>;
  connect(
    ctx: AdapterContext,
    opts?: {
      timeoutMs?: number;
      partyId?: PartyId;
      preferInstalled?: boolean;
      onDisplayUri?: (uri: string) => void;
    }
  ): Promise<AdapterConnectResult>;
  disconnect(ctx: AdapterContext, _session: Session): Promise<void>;
  restore(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>;
  signMessage(
    ctx: AdapterContext,
    session: Session,
    params: SignMessageParams
  ): Promise<SignedMessage>;
  signTransaction(
    _ctx: AdapterContext,
    _session: Session,
    _params: SignTransactionParams
  ): Promise<SignedTransaction>;
  submitTransaction(
    ctx: AdapterContext,
    session: Session,
    params: SubmitTransactionParams
  ): Promise<TxReceipt>;
  ledgerApi(
    ctx: AdapterContext,
    session: Session,
    params: LedgerApiParams
  ): Promise<LedgerApiResult>;
  private transportFor;
}

/**
 * Popup JSON-RPC transport for the Walley web wallet. Opens a centred popup,
 * waits for its `{ ready: true }`, then exchanges one origin-checked JSON-RPC
 * 2.0 request/response over `postMessage`. A popup closed early is a rejection.
 */
interface PopupSendOptions {
  /** Reject after this many ms if the user has not completed the flow. */
  timeoutMs?: number;
  /** Abort the flow (closes the popup, rejects the promise). */
  signal?: AbortSignal;
}
declare class WalleyPopupTransport {
  private readonly host;
  constructor(host: string);
  send<T>(path: string, method: string, params?: unknown, options?: PopupSendOptions): Promise<T>;
}

/**
 * Walley error classes — subclass the closest existing PartyLayer error and
 * carry diagnostic detail in `details`.
 */

/** No browser/popup environment (SSR, Node). Subclasses `WalletNotInstalledError`. */
declare class WalleyNotAvailableError extends WalletNotInstalledError {
  constructor(reason?: string);
}
/** Browser blocked the popup — a transport failure, not a user rejection. */
declare class WalleyPopupBlockedError extends TransportError {
  constructor(host: string);
}

/** Canonical wallet id used across the registry, SDK and adapter. */
declare const WALLEY_WALLET_ID = 'walley';
/** Marketing / install homepage shown in connect UIs. */
declare const WALLEY_HOMEPAGE = 'https://walley.cc';
/** Walley is a hosted web wallet, so "install" is just visiting the site. */
declare const WALLEY_INSTALL_URL = 'https://walley.cc';
/** Hosted Walley origin, keyed by Canton network. */
declare const WALLEY_HOSTS: Record<string, string>;
/** Networks the hosted Walley wallet is available on. */
declare const WALLEY_SUPPORTED_NETWORKS: readonly ['mainnet'];
/**
 * Walley signs every operation with an Ed25519 key derived from a WebAuthn
 * passkey (PRF extension). Surfaced in session metadata so dApps can tailor
 * copy ("approve in Touch ID / Face ID") instead of a generic prompt.
 */
declare const WALLEY_SIGNING_METHOD: 'webauthn-prf';
/** Popup paths on the Walley host, one per JSON-RPC surface. */
declare const WALLEY_POPUP_PATHS: {
  readonly connect: '/dapp/connect';
  readonly sign: '/dapp/sign';
  readonly execute: '/dapp/execute';
};
/** Resolve the Walley host; a self-hosted override wins, else the hosted wallet. */
declare function resolveWalleyHost(network: NetworkId, override?: string): string;

/**
 * Wire types for Walley's dApp popup bridge, mirroring the JSON-RPC surface of
 * `@k2flabs/walley-dapp-sdk`. Re-declared locally to keep the adapter dependency-light.
 */
/** Optional params accepted by the `connect` method. */
interface WalleyConnectParams {
  /** When set, Walley signs this message as part of the connect approval and
   *  returns the signature on {@link WalleyConnectResult.signature}. */
  signMessage?: {
    message: string;
  };
}
/** Resolved payload from the `/dapp/connect` popup. */
interface WalleyConnectResult {
  partyId: string;
  partyHint: string;
  publicKeyFingerprint: string;
  publicKeyBase64: string;
  networkId: string;
  /** Bearer token for `ledgerApi` calls. Short-lived; on a 401, re-connect. */
  accessToken?: string;
  /** Unix seconds at which `accessToken` expires. */
  expiresAt?: number;
  /** Base URL of the wallet's ledger proxy. */
  apiBaseUrl?: string;
  /** Base64 Ed25519 signature, present only when `connect` carried a
   *  `signMessage` request. */
  signature?: string;
}
/** Params for the `signMessage` method. */
interface WalleySignMessageParams {
  message: string;
}
/** Resolved payload from the `/dapp/sign` popup. */
interface WalleySignMessageResult {
  /** Base64 Ed25519 signature. */
  signature: string;
}
/** A disclosed contract forwarded with an execute request. */
interface WalleyDisclosedContract {
  templateId?: string;
  contractId?: string;
  createdEventBlob?: string;
  synchronizerId?: string;
}
/**
 * Params for the `prepareExecute` / `prepareExecuteAndWait` methods. Mirrors
 * CIP-0103 `PrepareExecuteParams`. `commands` is left as `unknown[]` because
 * the Daml command shape is application-specific.
 */
interface WalleyPrepareExecuteParams {
  commands: unknown[];
  commandId?: string;
  actAs?: string[];
  readAs?: string[];
  disclosedContracts?: WalleyDisclosedContract[];
  synchronizerId?: string;
  packageIdSelectionPreference?: string[];
}
/**
 * Resolved payload from `prepareExecuteAndWait`. Walley's current execute page
 * resolves `null` once the user approves; future versions are expected to
 * populate `updateId` / `commandId`, so both are read defensively.
 */
interface WalleyPrepareExecuteResult {
  updateId?: string;
  commandId?: string;
  completionOffset?: string;
}

export {
  type PopupSendOptions,
  WALLEY_HOMEPAGE,
  WALLEY_HOSTS,
  WALLEY_INSTALL_URL,
  WALLEY_POPUP_PATHS,
  WALLEY_SIGNING_METHOD,
  WALLEY_SUPPORTED_NETWORKS,
  WALLEY_WALLET_ID,
  WalleyAdapter,
  type WalleyAdapterConfig,
  type WalleyConnectParams,
  type WalleyConnectResult,
  type WalleyDisclosedContract,
  WalleyNotAvailableError,
  WalleyPopupBlockedError,
  WalleyPopupTransport,
  type WalleyPrepareExecuteParams,
  type WalleyPrepareExecuteResult,
  type WalleySignMessageParams,
  type WalleySignMessageResult,
  resolveWalleyHost,
};
