// API SURFACE SNAPSHOT — @partylayer/adapter-nightly
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point. DO NOT edit by hand. To intentionally accept a
// public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import * as _partylayer_core from '@partylayer/core';
import { WalletAdapter, CapabilityKey, AdapterDetectResult, AdapterContext, PartyId, AdapterConnectResult, Session, PersistedSession, SignMessageParams, SignedMessage, SignTransactionParams, SignedTransaction, SubmitTransactionParams, TxReceipt, LedgerApiParams, LedgerApiResult } from '@partylayer/core';

/** Sign request response types from Nightly wallet */
declare enum SignRequestResponseType {
    SIGN_REQUEST_APPROVED = "sign_request_approved",
    SIGN_REQUEST_REJECTED = "sign_request_rejected",
    SIGN_REQUEST_ERROR = "sign_request_error"
}
interface SignRequestResponse {
    type: SignRequestResponseType;
    data: {
        signature?: string;
        updateId?: string;
    } | {
        reason: string;
    } | {
        error: string;
    };
}
interface Instrument {
    id: string;
    admin: string;
}
interface TransactionCommand {
    command: unknown;
    disclosedContracts: unknown[];
}
interface CreateTransferCommandParams {
    receiverPartyId: string;
    amount: string;
    instrument: Instrument;
    memo?: string;
    expiryDate?: string;
}
/** The wallet object returned after successful connection */
interface NightlyCantonWallet {
    partyId: string;
    publicKey: string;
    signMessage: (message: string, onResponse: (response: SignRequestResponse) => void) => void;
    createTransferCommand: (params: CreateTransferCommandParams) => Promise<TransactionCommand>;
    submitTransactionCommand: (transactionCommand: TransactionCommand, onResponse: (response: SignRequestResponse) => void) => void;
    getPendingTransactions: () => Promise<unknown[] | null>;
    getHoldingUtxos: () => Promise<unknown[] | null>;
}
/** The injected provider at window.nightly.canton */
interface NightlyCantonProvider extends NightlyCantonWallet {
    connect: () => Promise<{
        partyId: string;
        publicKey: string;
    }>;
    disconnect: () => Promise<void>;
    isConnected: () => boolean;
}
declare global {
    interface Window {
        nightly?: {
            canton?: NightlyCantonProvider;
        };
    }
}
/**
 * Nightly Wallet adapter
 *
 * Implements WalletAdapter interface for Nightly Wallet's Canton support.
 * The wallet injects at window.nightly.canton and provides:
 * - connect/disconnect via Promise
 * - signMessage via callback
 * - transaction commands via callback
 * - session restore via isConnected()
 */
declare class NightlyAdapter implements WalletAdapter {
    readonly walletId: _partylayer_core.WalletId;
    readonly name = "Nightly";
    private wallet;
    getCapabilities(): CapabilityKey[];
    /**
     * Detect if Nightly wallet extension is installed.
     * Checks for window.nightly.canton provider.
     */
    detectInstalled(): Promise<AdapterDetectResult>;
    /**
     * Connect to Nightly Wallet.
     *
     * Calls window.nightly.canton.connect() which opens the extension
     * popup for user approval.
     */
    connect(ctx: AdapterContext, _opts?: {
        timeoutMs?: number;
        partyId?: PartyId;
    }): Promise<AdapterConnectResult>;
    /**
     * Disconnect from Nightly Wallet.
     */
    disconnect(ctx: AdapterContext, _session: Session): Promise<void>;
    /**
     * Restore session — check if Nightly is still connected.
     */
    restore(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>;
    /**
     * Sign a message.
     *
     * Nightly uses a callback-based signMessage API — we wrap it
     * in a Promise for the WalletAdapter interface.
     */
    signMessage(ctx: AdapterContext, session: Session, params: SignMessageParams): Promise<SignedMessage>;
    /**
     * Sign a transaction — not supported standalone.
     *
     * Nightly combines signing and submission via submitTransactionCommand.
     */
    signTransaction(_ctx: AdapterContext, _session: Session, _params: SignTransactionParams): Promise<SignedTransaction>;
    /**
     * Submit a transaction.
     *
     * Nightly uses callback-based submitTransactionCommand.
     * The signedTx should be a TransactionCommand object created via
     * createTransferCommand or createTransactionChoiceCommand.
     */
    submitTransaction(ctx: AdapterContext, session: Session, params: SubmitTransactionParams): Promise<TxReceipt>;
    /**
     * Proxy a Ledger API request through the Nightly Wallet.
     *
     * Nightly's canton provider may expose ledgerApi or a generic request()
     * method. We check at runtime — the interface is cast to include these
     * optional methods that may be present in newer wallet versions.
     */
    ledgerApi(ctx: AdapterContext, session: Session, params: LedgerApiParams): Promise<LedgerApiResult>;
}

export { NightlyAdapter };
