// API SURFACE SNAPSHOT — @partylayer/react-native/async-storage
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare function createAsyncStorage(): SessionStorage;
declare function createAsyncStorageAdapter(): StorageAdapter;
export { createAsyncStorage, createAsyncStorageAdapter };
import { SessionStorage } from '@partylayer/session';
import { StorageAdapter } from '@partylayer/core';
