// API SURFACE SNAPSHOT — @partylayer/adapter-starter
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point. DO NOT edit by hand. To intentionally accept a
// public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
/**
 * @partylayer/adapter-starter
 * Starter template for building PartyLayer wallet adapters
 */
export * from './adapter';
export * from './vendor';
//# sourceMappingURL=index.d.ts.map