// API SURFACE SNAPSHOT — @partylayer/react-native
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare function createAsyncStorage(asyncStorage?: RNAsyncStorage): SessionStorage;
declare function createAsyncStorageAdapter(asyncStorage?: RNAsyncStorage): StorageAdapter;
declare function createReactNativeClient(config: ReactNativeClientConfig): PartyLayerClient;
declare function createReactNativeDeepLinkPlatform(linking?: RNLinking): DeepLinkPlatform;
export { type RNAsyncStorage, type RNLinking, type ReactNativeClientConfig, createAsyncStorage, createAsyncStorageAdapter, createReactNativeClient, createReactNativeDeepLinkPlatform };
import { DeepLinkPlatform, StorageAdapter } from '@partylayer/core';
import { PartyLayerConfig, PartyLayerClient } from '@partylayer/sdk';
import { SessionStorage } from '@partylayer/session';
interface RNAsyncStorage { getItem(key: string): Promise<string | null>; setItem(key: string, value: string): Promise<void>; removeItem(key: string): Promise<void>; clear(): Promise<void>; }
interface RNLinking { openURL(url: string): Promise<unknown>; addEventListener(type: 'url', handler: (event: { url: string; }) => void): { remove(): void; }; getInitialURL(): Promise<string | null>; }
interface ReactNativeClientConfig extends PartyLayerConfig { asyncStorage?: RNAsyncStorage; }
