// API SURFACE SNAPSHOT — @partylayer/adapter-cantor8
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point. DO NOT edit by hand. To intentionally accept a
// public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import * as _partylayer_core from '@partylayer/core';
import { ConnectRequest, ConnectResponse, SignRequest, SignResponse, JobStatus, WalletAdapter, CapabilityKey, AdapterDetectResult, AdapterContext, AdapterConnectResult, SignMessageParams, SignTransactionParams } from '@partylayer/core';

/**
 * Cantor8 Vendor Integration Module
 *
 * This module abstracts vendor-specific endpoints and can be swapped
 * without breaking the adapter API.
 *
 * References:
 * - Cantor8 ecosystem: https://www.canton.network/ecosystem/cantor8
 * - Cantor8 site: https://cantor8.tech/about
 */

/**
 * Vendor configuration
 */
interface Cantor8VendorConfig {
    /** Deep link scheme (e.g., "cantor8") */
    deepLinkScheme?: string;
    /** Universal link base URL (e.g., "https://app.cantor8.tech") */
    universalLinkBase?: string;
    /** Connect endpoint path */
    connectEndpoint?: string;
    /** Sign endpoint path */
    signEndpoint?: string;
    /** Job status endpoint path (for async approvals) */
    statusEndpoint?: string;
    /** Redirect URI for callbacks */
    redirectUri?: string;
}
/**
 * Vendor module interface
 *
 * Implementations can be swapped without changing adapter code.
 */
interface Cantor8VendorModule {
    /**
     * Create connect URL
     */
    createConnectUrl(request: ConnectRequest, config: Cantor8VendorConfig): string;
    /**
     * Parse connect callback
     */
    parseConnectCallback(callbackData: unknown, expectedState: string): ConnectResponse;
    /**
     * Create sign URL
     */
    createSignUrl(request: SignRequest, config: Cantor8VendorConfig): string;
    /**
     * Parse sign callback
     */
    parseSignCallback(callbackData: unknown, expectedState: string): SignResponse;
    /**
     * Poll job status (optional, for async approvals)
     */
    pollJobStatus?(jobId: string, statusUrl: string, timeoutMs: number): Promise<JobStatus>;
}

/**
 * Cantor8 adapter configuration
 */
interface Cantor8AdapterConfig {
    /** Vendor module (defaults to stub) */
    vendorModule?: Cantor8VendorModule;
    /** Vendor configuration */
    vendorConfig?: Cantor8VendorConfig;
    /** Use mock transport in development */
    useMockTransport?: boolean;
}
/**
 * Cantor8 Wallet Adapter
 */
declare class Cantor8Adapter implements WalletAdapter {
    readonly walletId: _partylayer_core.WalletId;
    readonly name = "Cantor8";
    private vendorModule;
    private vendorConfig;
    private transport;
    constructor(config?: Cantor8AdapterConfig);
    getCapabilities(): CapabilityKey[];
    detectInstalled(): Promise<AdapterDetectResult>;
    connect(ctx: AdapterContext, opts?: {
        timeoutMs?: number;
        partyId?: _partylayer_core.PartyId;
    }): Promise<AdapterConnectResult>;
    disconnect(_ctx: AdapterContext, _session: _partylayer_core.Session): Promise<void>;
    restore(_ctx: AdapterContext, persisted: _partylayer_core.PersistedSession): Promise<_partylayer_core.Session | null>;
    signMessage(ctx: AdapterContext, session: _partylayer_core.Session, params: SignMessageParams): Promise<_partylayer_core.SignedMessage>;
    signTransaction(ctx: AdapterContext, session: _partylayer_core.Session, params: SignTransactionParams): Promise<_partylayer_core.SignedTransaction>;
    /**
     * Generate random state nonce
     */
    private generateState;
}

export { Cantor8Adapter, type Cantor8AdapterConfig };
