// API SURFACE SNAPSHOT — @partylayer/adapter-wintip
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare class WintipAdapter implements WalletAdapter { readonly walletId: _partylayer_core.WalletId; readonly name = "Wintip Wallet"; getCapabilities(): CapabilityKey[]; detectInstalled(): Promise<AdapterDetectResult>; connect(ctx: AdapterContext, _opts?: { timeoutMs?: number; partyId?: PartyId; }): Promise<AdapterConnectResult>; disconnect(ctx: AdapterContext, _session: Session): Promise<void>; restore(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>; submitTransaction(ctx: AdapterContext, session: Session, params: SubmitTransactionParams): Promise<TxReceipt>; ledgerApi(ctx: AdapterContext, session: Session, params: LedgerApiParams): Promise<LedgerApiResult>; on(event: AdapterEventName, handler: (payload: unknown) => void): () => void; }
declare class WintipNotInstalledError extends WalletNotInstalledError { constructor(reason?: string); }
declare const WINTIP_HOMEPAGE = "https://wintip.cc";
declare const WINTIP_INSTALL_URL = "https://wallet.wintip.cc/register";
declare const WINTIP_PROVIDER_ID = "wintip-wallet";
declare const WINTIP_PROVIDER_SCRIPT_URL = "https://wallet.wintip.cc/wintip-provider.js";
declare const WINTIP_SUPPORTED_NETWORKS: readonly [ "mainnet" ];
declare const WINTIP_WALLET_ID = "wintip";
declare const WINTIP_WALLET_URL = "https://wallet.wintip.cc";
declare const WintipRpcErrorCode: { readonly METHOD_NOT_FOUND: -32601; readonly INVALID_PARAMS: -32602; readonly USER_REJECTED: 4001; readonly UNAUTHORIZED: 4100; readonly UNSUPPORTED_METHOD: 4200; readonly DISCONNECTED: 4900; readonly TRANSACTION_REJECTED: -32003; };
declare function isWintipRpcError(err: unknown): err is WintipRpcErrorLike;
declare function mapWintipError(err: unknown, context: ErrorMappingContext): PartyLayerError;
export { WINTIP_HOMEPAGE, WINTIP_INSTALL_URL, WINTIP_PROVIDER_ID, WINTIP_PROVIDER_SCRIPT_URL, WINTIP_SUPPORTED_NETWORKS, WINTIP_WALLET_ID, WINTIP_WALLET_URL, type WintipAccount, WintipAdapter, type WintipConnectResult, type WintipEventListener, WintipNotInstalledError, type WintipPrepareExecuteResponse, type WintipPrepareSubmissionRequest, type WintipProviderInfo, WintipRpcErrorCode, type WintipStatusEvent, type WintipTxChangedEvent, type WintipTxResult, isWintipRpcError, mapWintipError };
import * as _partylayer_core from '@partylayer/core';
import { WalletAdapter, CapabilityKey, AdapterDetectResult, AdapterContext, PartyId, AdapterConnectResult, Session, PersistedSession, SubmitTransactionParams, TxReceipt, LedgerApiParams, LedgerApiResult, AdapterEventName, WalletNotInstalledError, ErrorMappingContext, PartyLayerError } from '@partylayer/core';
interface WintipAccount { partyId: string; status: 'initializing' | 'allocated' | 'removed'; hint: string; publicKey: string; namespace: string; networkId: string; signingProviderId: string; primary: boolean; disabled: boolean; }
interface WintipConnectResult { isConnected: boolean; isNetworkConnected: boolean; reason?: string; }
interface WintipPrepareExecuteResponse { tx: WintipTxResult; }
interface WintipPrepareSubmissionRequest { commands: unknown[]; commandId?: string; actAs?: string[]; readAs?: string[]; disclosedContracts?: unknown[]; synchronizerId?: string; packageIdSelectionPreference?: string[]; }
interface WintipProviderInfo { id: string; version: string; providerType: 'browser' | 'desktop' | 'mobile' | 'remote'; }
interface WintipRpcErrorLike { code: number; message: string; data?: unknown; }
interface WintipStatusEvent { provider: WintipProviderInfo; connection: WintipConnectResult; network?: { networkId: string; }; }
interface WintipTxChangedEvent { status: 'pending' | 'executed' | 'failed'; commandId: string; updateId?: string; completionOffset?: number; payload?: { updateId?: string; completionOffset?: number; }; error?: { code: number; message: string; data?: unknown; }; }
interface WintipTxResult { status: 'executed' | 'failed'; commandId: string; updateId?: string; completionOffset?: number; payload?: { updateId?: string; completionOffset?: number; }; }
type WintipEventListener = (...args: unknown[]) => void;
