// API SURFACE SNAPSHOT — @partylayer/testing/query
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import { QueryClient, QueryClientConfig, QueryKey } from '@tanstack/query-core';
import { O as OfflineHarness, e as MockWalletConfig } from './offline-CELeTEq9.js';
import { SessionStoreOptions } from '@partylayer/session';
import '@partylayer/core';
import '@partylayer/provider';

/**
 * TanStack Query test utilities — `@partylayer/testing/query`.
 *
 * Subpath entry so the main package stays dependency-free for non-Query
 * consumers. `@tanstack/query-core` is an OPTIONAL peer; install it only if you
 * import from here.
 */

/** A QueryClient with test-friendly defaults (no retries, no caching window). */
declare function createTestQueryClient(overrides?: QueryClientConfig): QueryClient;
interface QueryStateView<T> {
  readonly data: T | undefined;
  readonly status: 'pending' | 'error' | 'success';
  readonly fetchStatus: 'fetching' | 'paused' | 'idle';
  readonly isInvalidated: boolean;
}
/** Read a query's current cache state (data + status + invalidation flag). */
declare function getQueryState<T>(client: QueryClient, key: QueryKey): QueryStateView<T>;
/** True when the query at `key` is currently marked invalidated. */
declare function expectInvalidated(client: QueryClient, key: QueryKey): boolean;
interface OptimisticRollback<T> {
  /** The cache value captured before the optimistic write. */
  readonly snapshot: T | undefined;
  /** Apply an optimistic value to the cache. */
  apply(next: T): void;
  /** Restore the captured snapshot (rollback). */
  rollback(): void;
  /** Current cache value at the key. */
  current(): T | undefined;
}
/**
 * Capture a key's value, then drive an optimistic apply → rollback so a test can
 * assert both the optimistic write and that rollback restored the snapshot.
 */
declare function trackOptimisticRollback<T>(
  client: QueryClient,
  key: QueryKey
): OptimisticRollback<T>;
/** Offline harness (mock wallet + session store) plus a test QueryClient. */
interface QueryHarness extends OfflineHarness {
  readonly queryClient: QueryClient;
}
/** Query-inclusive composition of {@link createOfflineHarness}. */
declare function createQueryHarness(config?: {
  wallet?: MockWalletConfig;
  session?: Partial<SessionStoreOptions>;
  query?: QueryClientConfig;
}): QueryHarness;

export {
  type OptimisticRollback,
  type QueryHarness,
  type QueryStateView,
  createQueryHarness,
  createTestQueryClient,
  expectInvalidated,
  getQueryState,
  trackOptimisticRollback,
};
