// API SURFACE SNAPSHOT — @partylayer/react-native/ui
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare function BackIcon({ color, size }: { color: string; size?: number; }): react_jsx_runtime.JSX.Element;
declare function CloseIcon({ color, size }: { color: string; size?: number; }): react_jsx_runtime.JSX.Element;
declare function ConnectButton({ client, theme, label, testID }: ConnectButtonProps): react_jsx_runtime.JSX.Element;
declare function ErrorIcon({ color, size }: { color: string; size?: number; }): react_jsx_runtime.JSX.Element;
declare function Spinner({ color, size }: { color: string; size?: 'small' | 'large' | number; }): react_jsx_runtime.JSX.Element;
declare function WalletIcon({ url, format, size, theme, testID }: WalletIconProps): react_jsx_runtime.JSX.Element;
declare function WalletList({ client, theme, visible, onClose, testID }: WalletListProps): react_jsx_runtime.JSX.Element;
declare function truncateParty(partyId: string): string;
export { BackIcon, CloseIcon, ConnectButton, type ConnectButtonProps, ErrorIcon, Spinner, WalletIcon, type WalletIconProps, WalletList, type WalletListProps, truncateParty };
import * as react_jsx_runtime from 'react/jsx-runtime';
import { PartyLayerClient } from '@partylayer/sdk';
import { b as ReactNativeTheme, I as IconFormat } from './icons-DdH3oA7q.js';
interface ConnectButtonProps { client: PartyLayerClient; theme: ReactNativeTheme; label?: string; testID?: string; }
interface WalletIconProps { url?: string; format: IconFormat; size: number; theme: ReactNativeTheme; testID?: string; }
interface WalletListProps { client: PartyLayerClient; theme: ReactNativeTheme; visible: boolean; onClose: () => void; testID?: string; }
