// API SURFACE SNAPSHOT — @partylayer/sdk
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import * as _partylayer_core from '@partylayer/core';
import {
  WalletAdapter,
  NetworkId,
  StorageAdapter,
  CryptoAdapter,
  TelemetryAdapter,
  LoggerAdapter,
  WalletId,
  Session,
  SessionId,
  TransactionHash,
  TransactionStatus,
  WalletInfo,
  SignMessageParams,
  SignedMessage,
  SignTransactionParams,
  SignedTransaction,
  SubmitTransactionParams,
  TxReceipt,
  LedgerApiParams,
  LedgerApiResult,
} from '@partylayer/core';
export {
  AdapterConnectResult,
  AdapterContext,
  AdapterDetectResult,
  PartyLayerError as CantonConnectError,
  CapabilityKey,
  CapabilityNotSupportedError,
  ENABLEMENT_METRICS,
  ERROR_METRICS,
  ErrorCode,
  InternalError,
  LedgerApiParams,
  LedgerApiResult,
  METRICS,
  MetricName,
  MetricsPayload,
  NetworkId,
  OriginNotAllowedError,
  PartyId,
  PartyLayerError,
  REGISTRY_METRICS,
  RegistryFetchFailedError,
  RegistrySchemaInvalidError,
  RegistryVerificationFailedError,
  Session,
  SessionExpiredError,
  SessionId,
  SignMessageParams,
  SignTransactionParams,
  SignedMessage,
  SignedTransaction,
  SubmitTransactionParams,
  TimeoutError,
  TransactionStatus,
  TransportError,
  TxReceipt,
  UserRejectedError,
  WalletAdapter,
  WalletId,
  WalletInfo,
  WalletNotFoundError,
  WalletNotInstalledError,
  errorMetricName,
} from '@partylayer/core';
import { RegistryClient, RegistryStatus } from '@partylayer/registry-client';
export {
  Cip0103StatusForDetection,
  Cip0103Support,
  ProviderDetection,
  ProviderMatcher,
  RegistryStatus,
  deriveGenericWalletName,
  findMatchingWallet,
  findMatchingWalletInfo,
  isCip0103Native,
  matchesProviderDetection,
} from '@partylayer/registry-client';
export {
  CANTON_NETWORKS,
  CIP0103Account,
  CIP0103ConnectResult,
  CIP0103Event,
  CIP0103EventBus,
  CIP0103Method,
  CIP0103Network,
  CIP0103Provider,
  CIP0103StatusEvent,
  CIP0103TxChangedEvent,
  CIP0103TxStatus,
  CIP0103_EVENTS,
  CIP0103_MANDATORY_METHODS,
  CIP0103_METHODS,
  DiscoveredProvider,
  JSON_RPC_ERRORS,
  PartyLayerProvider,
  PartyLayerProviderOptions,
  ProviderRpcError,
  RPC_ERRORS,
  createProviderBridge,
  discoverInjectedProviders,
  fromCAIP2Network,
  isCIP0103Provider,
  isValidCAIP2,
  toCAIP2Network,
  waitForProvider,
} from '@partylayer/provider';
export {
  BronAdapter,
  BronAdapterConfig,
  BronApiConfig,
  BronAuthConfig,
} from '@partylayer/adapter-bron';
export { Cantor8Adapter } from '@partylayer/adapter-cantor8';
export { ConsoleAdapter } from '@partylayer/adapter-console';
export { LoopAdapter } from '@partylayer/adapter-loop';
export { NightlyAdapter } from '@partylayer/adapter-nightly';
export { SendAdapter } from '@partylayer/adapter-send';

/**
 * Configuration types for PartyLayer SDK
 */

/**
 * Default registry URL for PartyLayer
 * This points to the official registry endpoint.
 */
declare const DEFAULT_REGISTRY_URL = 'https://registry.partylayer.xyz';
/**
 * Telemetry configuration for opt-in metrics collection
 *
 * @since 0.3.0
 */
interface TelemetryConfig {
  /**
   * Enable telemetry collection
   * @default false
   */
  enabled: boolean;
  /**
   * Metrics backend endpoint URL
   * If not provided, metrics are collected but not sent
   */
  endpoint?: string;
  /**
   * Sampling rate (0.0 to 1.0)
   * @default 1.0 (100% of events)
   */
  sampleRate?: number;
  /**
   * Application identifier (will be hashed for privacy)
   * Used to calculate Monthly Active dApps (MAD)
   */
  appId?: string;
  /**
   * Include hashed origin in metrics
   * @default false
   */
  includeOrigin?: boolean;
  /**
   * Number of events to buffer before sending
   * @default 10
   */
  batchSize?: number;
  /**
   * Interval to flush metrics in milliseconds
   * @default 30000 (30 seconds)
   */
  flushIntervalMs?: number;
  /**
   * Network to include in metrics
   * If not provided, uses the SDK's configured network
   */
  network?: NetworkId;
}
/**
 * Adapter class type (for instantiation)
 */
type AdapterClass = new () => WalletAdapter;
/**
 * PartyLayer configuration
 */
interface PartyLayerConfig {
  /**
   * Registry URL (optional)
   * @default 'https://registry.partylayer.xyz/v1/wallets.json'
   */
  registryUrl?: string;
  /** Registry channel */
  channel?: 'stable' | 'beta';
  /** Default network */
  network: NetworkId;
  /**
   * Wallet adapters to register (OPTIONAL)
   *
   * By default, ALL built-in adapters are automatically registered:
   * - ConsoleAdapter (Console Wallet - browser extension)
   * - LoopAdapter (5N Loop - QR code / popup)
   * - Cantor8Adapter (Cantor8 - deep link transport)
   *
   * Note: BronAdapter requires OAuth config and is NOT included by default.
   *
   * Only provide this if you want to customize which adapters to use.
   *
   * @example
   * ```typescript
   * // Default: all adapters (recommended)
   * const client = createPartyLayer({
   *   network: 'devnet',
   *   app: { name: 'My dApp' },
   *   // adapters not specified = all built-in adapters (Console, Loop, Cantor8)
   * });
   *
   * // Custom: only specific adapters
   * import { ConsoleAdapter } from '@partylayer/sdk';
   * const client = createPartyLayer({
   *   adapters: [new ConsoleAdapter()], // Only Console Wallet
   *   // ...
   * });
   *
   * // With Bron (enterprise wallet with OAuth)
   * import { BronAdapter, getBuiltinAdapters } from '@partylayer/sdk';
   * const client = createPartyLayer({
   *   adapters: [
   *     ...getBuiltinAdapters(),
   *     new BronAdapter({ auth: {...}, api: {...} }),
   *   ],
   *   // ...
   * });
   * ```
   */
  adapters?: (WalletAdapter | AdapterClass)[];
  /** Storage adapter (default: browser localStorage-based encrypted) */
  storage?: StorageAdapter;
  /** Crypto adapter (default: WebCrypto) */
  crypto?: CryptoAdapter;
  /** Registry public keys for signature verification (ed25519) */
  registryPublicKeys?: string[];
  /**
   * Telemetry configuration or adapter
   *
   * Can be either:
   * - TelemetryConfig object for built-in metrics collection
   * - TelemetryAdapter instance for custom telemetry
   *
   * @default undefined (telemetry disabled)
   * @since 0.3.0 - Added TelemetryConfig support
   */
  telemetry?: TelemetryAdapter | TelemetryConfig;
  /** Logger adapter (optional) */
  logger?: LoggerAdapter;
  /** Application metadata */
  app: {
    /** Application name */
    name: string;
    /** Origin (for origin binding checks, defaults to window.location.origin) */
    origin?: string;
  };
}
/**
 * Connect options
 */
interface ConnectOptions {
  /** Specific wallet ID to connect to */
  walletId?: WalletId;
  /** Prefer installed wallets */
  preferInstalled?: boolean;
  /** Allow only specific wallets */
  allowWallets?: WalletId[];
  /** Required capabilities */
  requiredCapabilities?: string[];
  /** Timeout in milliseconds */
  timeoutMs?: number;
}
/**
 * Wallet filter options
 */
interface WalletFilter {
  /** Required capabilities */
  requiredCapabilities?: string[];
  /** Include experimental wallets */
  includeExperimental?: boolean;
}

/**
 * Event types for PartyLayer SDK
 */

/**
 * Registry updated event
 */
interface RegistryUpdatedEvent {
  type: 'registry:updated';
  channel: 'stable' | 'beta';
  version: string;
}
/**
 * Registry status event
 */
interface RegistryStatusEvent {
  type: 'registry:status';
  status: {
    source: 'network' | 'cache';
    verified: boolean;
    channel: 'stable' | 'beta';
    sequence: number;
    stale: boolean;
    fetchedAt: number;
    etag?: string;
    error?: Error;
  };
}
/**
 * Session connected event
 */
interface SessionConnectedEvent {
  type: 'session:connected';
  session: Session;
}
/**
 * Session disconnected event
 */
interface SessionDisconnectedEvent {
  type: 'session:disconnected';
  sessionId: SessionId;
  reason?: string;
}
/**
 * Session expired event
 */
interface SessionExpiredEvent {
  type: 'session:expired';
  sessionId: SessionId;
}
/**
 * Transaction status event
 */
interface TxStatusEvent {
  type: 'tx:status';
  sessionId: SessionId;
  txId: TransactionHash;
  status: TransactionStatus;
  raw?: unknown;
}
/**
 * Error event
 */
interface ErrorEvent {
  type: 'error';
  error: Error;
}
/**
 * All event types
 */
type PartyLayerEvent =
  | RegistryUpdatedEvent
  | RegistryStatusEvent
  | SessionConnectedEvent
  | SessionDisconnectedEvent
  | SessionExpiredEvent
  | TxStatusEvent
  | ErrorEvent;
/**
 * Event handler type
 */
type EventHandler<T extends PartyLayerEvent = PartyLayerEvent> = (event: T) => void | Promise<void>;

/**
 * PartyLayer Client
 *
 * Main client interface for dApps to interact with Canton wallets.
 */
declare class PartyLayerClient {
  private config;
  private adapters;
  private eventHandlers;
  private activeSession;
  readonly registryClient: RegistryClient;
  private logger;
  private crypto;
  private storage;
  private telemetry?;
  private origin;
  constructor(config: PartyLayerConfig);
  /**
   * Register a wallet adapter
   *
   * @internal
   * This is used internally by the SDK to register adapters.
   * In production, adapters would be auto-registered via registry.
   */
  registerAdapter(adapter: WalletAdapter): void;
  /**
   * Look up a registered adapter by wallet id.
   *
   * Returns the adapter instance when one is registered for the given
   * `walletId`, or `undefined` otherwise. Intended for UI integrations
   * that need to call `adapter.detectInstalled()` directly to render a
   * per-wallet readiness indicator (instead of duplicating
   * transport-specific install detection logic in the picker). The
   * returned adapter is the same instance used internally for connect /
   * sign / submit flows; do not mutate it.
   *
   * Accepts both raw string ids and the branded `WalletId` form so
   * consumers can pass `walletInfo.walletId` or a string literal
   * interchangeably.
   */
  getAdapter(walletId: string | WalletId): WalletAdapter | undefined;
  /**
   * List available wallets
   */
  listWallets(filter?: WalletFilter): Promise<WalletInfo[]>;
  /**
   * Connect to a wallet
   */
  connect(options?: ConnectOptions): Promise<Session>;
  /**
   * Disconnect from wallet
   */
  disconnect(): Promise<void>;
  /**
   * Get active session
   */
  getActiveSession(): Promise<Session | null>;
  /**
   * Sign a message
   */
  signMessage(params: SignMessageParams): Promise<SignedMessage>;
  /**
   * Sign a transaction
   */
  signTransaction(params: SignTransactionParams): Promise<SignedTransaction>;
  /**
   * Submit a transaction
   */
  submitTransaction(params: SubmitTransactionParams): Promise<TxReceipt>;
  /**
   * Proxy a JSON Ledger API request through the active wallet adapter
   */
  ledgerApi(params: LedgerApiParams): Promise<LedgerApiResult>;
  /**
   * Subscribe to events
   */
  on<T extends PartyLayerEvent>(event: T['type'], handler: EventHandler<T>): () => void;
  /**
   * Unsubscribe from events
   */
  off<T extends PartyLayerEvent>(event: T['type'], handler: EventHandler<T>): void;
  /**
   * Get a CIP-0103 Provider backed by this client.
   *
   * This bridge routes all request() calls through the existing
   * PartyLayerClient methods and maps events to CIP-0103 format.
   *
   * The bridge implements the full CIP-0103 specification:
   * - All 10 mandatory methods including `ledgerApi` (when adapter supports it)
   * - Full transaction lifecycle: pending -> signed -> executed/failed
   * - All CIP-0103 events: statusChanged, accountsChanged, txChanged, connected
   *
   * **Note:** Async wallets (userUrl pattern) are not supported through the
   * bridge. For async wallet support, use `PartyLayerProvider` directly.
   *
   * @returns CIP-0103 compliant Provider
   */
  asProvider(): _partylayer_core.CIP0103Provider;
  /**
   * Destroy client and cleanup
   */
  destroy(): void;
  /**
   * Create adapter context
   */
  private createAdapterContext;
  /**
   * Persist session to storage
   */
  private persistSession;
  /**
   * Remove session from storage.
   *
   * Accepts a sessionId for call-site symmetry, but since the SDK tracks one
   * active session we always remove the single SESSION_STORAGE_KEY.
   */
  private removeSession;
  /**
   * Restore session from storage
   */
  private restoreSession;
  /**
   * Update registry status and emit event
   */
  private updateRegistryStatus;
  /**
   * Get registry status
   */
  getRegistryStatus(): RegistryStatus | null;
  /**
   * Emit event to handlers
   */
  private emit;
}
/**
 * Create PartyLayer client
 *
 * This is the main entry point for dApps.
 *
 * @example
 * ```typescript
 * const client = createPartyLayer({
 *   registryUrl: 'https://registry.partylayer.xyz',
 *   channel: 'stable',
 *   network: 'devnet',
 *   app: { name: 'My dApp' }
 * });
 *
 * const session = await client.connect();
 * ```
 */
declare function createPartyLayer(config: PartyLayerConfig): PartyLayerClient;

/**
 * Built-in wallet adapters
 *
 * These adapters are automatically registered when creating a PartyLayer client.
 * dApp developers don't need to install or configure these separately.
 */

/**
 * Get all built-in adapters
 *
 * This function returns instances of all supported wallet adapters.
 * Called automatically by createPartyLayer() unless custom adapters are provided.
 *
 * Included adapters:
 * - ConsoleAdapter: Console Wallet browser extension + mobile (combined mode)
 * - LoopAdapter: 5N Loop mobile/web wallet
 * - Cantor8Adapter: Cantor8 wallet with deep link transport
 * - NightlyAdapter: Nightly multichain wallet with Canton support
 * - SendAdapter: Send Canton Wallet (passkey / WebAuthn-PRF, beta) — also
 *     injects at `window.canton`; the adapter's kernel.id guard keeps it
 *     and Console-spec wallets from claiming each other's provider.
 *
 * Note: ConsoleAdapter defaults to 'combined' mode which supports both browser
 * extension and mobile wallet connect (QR code / deep link). To restrict to
 * extension-only, pass { target: 'local' } to the constructor.
 *
 * Note: BronAdapter is NOT included by default because it requires OAuth configuration.
 * To use Bron, install @partylayer/adapter-bron and register it manually.
 */
declare function getBuiltinAdapters(): WalletAdapter[];

/**
 * Metrics Telemetry Adapter
 *
 * A privacy-safe telemetry adapter that collects metrics for
 * ecosystem health monitoring and usage reporting.
 *
 * Features:
 * - Opt-in by default (disabled unless explicitly enabled)
 * - Privacy-safe payloads (no PII, hashed identifiers)
 * - Batched sending to reduce network overhead
 * - Configurable sampling rate
 * - Automatic flush on interval or batch size
 *
 * @since 0.3.0
 */

/**
 * Metrics Telemetry Adapter
 *
 * Implements TelemetryAdapter interface with metrics-specific functionality.
 */
declare class MetricsTelemetryAdapter implements TelemetryAdapter {
  private config;
  private metrics;
  private buffer;
  private flushTimer;
  private appIdHash;
  private originHash;
  private initialized;
  constructor(config: TelemetryConfig);
  /**
   * Initialize async components (hashing)
   */
  private initialize;
  /**
   * Check if telemetry is enabled
   */
  isEnabled(): boolean;
  /**
   * Track a named event (TelemetryAdapter interface)
   */
  track(event: string, properties?: Record<string, unknown>): void;
  /**
   * Track an error (TelemetryAdapter interface)
   */
  error(error: Error, properties?: Record<string, unknown>): void;
  /**
   * Increment a metric counter
   */
  increment(metric: string, value?: number): void;
  /**
   * Set a gauge metric value
   */
  gauge(metric: string, value: number): void;
  /**
   * Buffer an event for batched sending
   */
  private bufferEvent;
  /**
   * Flush buffered metrics to backend
   */
  flush(): Promise<void>;
  /**
   * Get current metrics snapshot (for testing/debugging)
   */
  getMetrics(): Record<string, number>;
  /**
   * Reset all metrics (for testing)
   */
  reset(): void;
  /**
   * Destroy the adapter (cleanup timers)
   */
  destroy(): void;
}
/**
 * Check if a value is a TelemetryConfig object
 */
declare function isTelemetryConfig(value: unknown): value is TelemetryConfig;
/**
 * Create a TelemetryAdapter from config
 *
 * If config is already a TelemetryAdapter, returns it.
 * If config is a TelemetryConfig, creates a MetricsTelemetryAdapter.
 */
declare function createTelemetryAdapter(
  config: TelemetryAdapter | TelemetryConfig | undefined
): TelemetryAdapter | undefined;

export {
  type AdapterClass,
  PartyLayerClient as CantonConnectClient,
  type PartyLayerConfig as CantonConnectConfig,
  type PartyLayerEvent as CantonConnectEvent,
  type ConnectOptions,
  DEFAULT_REGISTRY_URL,
  type ErrorEvent,
  type EventHandler,
  MetricsTelemetryAdapter,
  PartyLayerClient,
  type PartyLayerConfig,
  type PartyLayerEvent,
  type RegistryUpdatedEvent,
  type SessionConnectedEvent,
  type SessionDisconnectedEvent,
  type SessionExpiredEvent,
  type TelemetryConfig,
  type TxStatusEvent,
  type WalletFilter,
  PartyLayerClient as _PartyLayerClientInternal,
  createPartyLayer as createCantonConnect,
  createPartyLayer,
  createTelemetryAdapter,
  getBuiltinAdapters,
  isTelemetryConfig,
};
