// API SURFACE SNAPSHOT — @partylayer/vue
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import { InjectionKey, Plugin, ComputedRef } from 'vue';
import {
  SessionStore,
  SessionStoreOptions,
  SessionAccount,
  SessionStatus,
  SessionState,
  SessionEvent,
} from '@partylayer/session';
import { CIP0103Provider } from '@partylayer/core';

/**
 * Session store provisioning for Vue — `provideSessionStore` (the core) and a
 * thin `createPartyLayerSession` plugin that wraps the same provide, so there is
 * a single source of truth (one injection key, one store-resolution path).
 *
 * Ownership rule:
 *   - Built from config → THIS layer owns the lifecycle: `init()` runs
 *     client-only (`onMounted`), `destroy()` on scope/app teardown.
 *   - A PRE-BUILT store → its lifecycle belongs to the caller; we NEVER
 *     `init()`/`destroy()` it.
 *
 * SSR-safe: the store is constructed without DOM access; `init()` is deferred to
 * `onMounted` (client only), so server rendering never touches the wallet.
 */

/** Injection key for the shared session store (or `null` when none provided). */
declare const SESSION_STORE_KEY: InjectionKey<SessionStore | null>;
/** Either a pre-built store, or config to build one (provider + store options). */
type ProvideSessionConfig =
  | SessionStore
  | ({
      provider: CIP0103Provider;
    } & Partial<SessionStoreOptions>);
/**
 * Provide a session store to descendant composables. Call in a component
 * `setup()` (e.g. your root). Returns the store for direct use if needed.
 *
 * When built from config, lifecycle is owned here (client-only `init()` on
 * mount, `destroy()` on scope teardown). A pre-built store is left untouched.
 */
declare function provideSessionStore(config: ProvideSessionConfig): SessionStore;
/**
 * Vue plugin form — a THIN wrapper over the same provide/resolution, for
 * `app.use(...)`. Owned stores `init()` on the client at install and `destroy()`
 * when the app unmounts.
 */
declare function createPartyLayerSession(config: ProvideSessionConfig): Plugin;
/** Internal: read the provided store, or `null` if none (SSR / outside provider). */
declare function injectSessionStore(): SessionStore | null;

/**
 * Vue composables over the `@partylayer/session` store. Wagmi/React parity:
 * `useSession` (reactive state + actions), `useAccount`, `useAccountEffect`.
 *
 * Each composable derives individual `ComputedRef`s from ONE internal
 * `shallowRef<SessionState>` fed by a single `store.subscribe`, cleaned up via
 * `onScopeDispose` (no leak after unmount). Returning refs — not a `reactive()`
 * object — means destructuring keeps reactivity.
 *
 * SSR-safe: with no provided store the refs report a disconnected session and
 * the actions are no-ops; nothing touches `window`.
 */

/** wagmi-parity chain handle derived from the CAIP-2 networkId. */
interface SessionChain {
  id: string;
}
interface UseSessionReturn {
  status: ComputedRef<SessionStatus>;
  account: ComputedRef<SessionAccount | null>;
  accounts: ComputedRef<readonly SessionAccount[]>;
  networkId: ComputedRef<string | null>;
  lastError: ComputedRef<Error | null>;
  isConnected: ComputedRef<boolean>;
  isConnecting: ComputedRef<boolean>;
  isReconnecting: ComputedRef<boolean>;
  isDisconnected: ComputedRef<boolean>;
  /** Connect via the store (mirrors the store's own signature exactly). */
  connect(params?: Record<string, unknown>): Promise<SessionState>;
  disconnect(): Promise<void>;
  restore(): Promise<SessionState>;
  /** Subscribe to a structured resilience/sync event (narrowed by `event`). */
  on<T extends SessionEvent['type']>(
    event: T,
    handler: (
      event: Extract<
        SessionEvent,
        {
          type: T;
        }
      >
    ) => void
  ): () => void;
}
/** Reactive session state + bound actions. */
declare function useSession(): UseSessionReturn;
interface UseAccountReturn {
  party: ComputedRef<string | null>;
  /** wagmi-parity alias of `party`. */
  address: ComputedRef<string | null>;
  account: ComputedRef<SessionAccount | null>;
  accounts: ComputedRef<readonly SessionAccount[]>;
  status: ComputedRef<SessionStatus>;
  isConnected: ComputedRef<boolean>;
  isConnecting: ComputedRef<boolean>;
  isReconnecting: ComputedRef<boolean>;
  isDisconnected: ComputedRef<boolean>;
  networkId: ComputedRef<string | null>;
  chain: ComputedRef<SessionChain | null>;
  lastError: ComputedRef<Error | null>;
}
/** Reactive active-account view (wagmi parity). */
declare function useAccount(): UseAccountReturn;
interface UseAccountEffectParameters {
  /** Fired on a transition INTO `connected` (once the account is available). */
  onConnect?: (data: {
    account: SessionAccount | null;
    accounts: readonly SessionAccount[];
    networkId: string | null;
  }) => void;
  /** Fired on a transition `connected → disconnected`. */
  onDisconnect?: () => void;
  /** Fired when the active PRIMARY party changes (a switch, not a reorder). */
  onPartyChanged?: (data: { previous: string | null; current: string | null }) => void;
}
/**
 * Fire side-effects on session transitions — no render churn. Auto-cleans on
 * scope teardown (`onScopeDispose`). No-op when no store is provided.
 */
declare function useAccountEffect(parameters?: UseAccountEffectParameters): void;

export {
  type ProvideSessionConfig,
  SESSION_STORE_KEY,
  type SessionChain,
  type UseAccountEffectParameters,
  type UseAccountReturn,
  type UseSessionReturn,
  createPartyLayerSession,
  injectSessionStore,
  provideSessionStore,
  useAccount,
  useAccountEffect,
  useSession,
};
