// API SURFACE SNAPSHOT — @partylayer/adapter-console
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import * as _partylayer_core from '@partylayer/core';
import {
  WalletAdapter,
  CapabilityKey,
  AdapterDetectResult,
  AdapterContext,
  PartyId,
  AdapterConnectResult,
  Session,
  PersistedSession,
  SignMessageParams,
  SignedMessage,
  SignTransactionParams,
  SignedTransaction,
  SubmitTransactionParams,
  TxReceipt,
  LedgerApiParams,
  LedgerApiResult,
} from '@partylayer/core';

/**
 * Connection target for Console Wallet.
 *
 * - 'local'    — Browser extension only (postMessage)
 * - 'remote'   — Mobile wallet only (QR code / deep link relay)
 * - 'combined' — Auto-detect: extension preferred, mobile fallback (default)
 */
type ConsoleConnectionTarget = 'local' | 'remote' | 'combined';
/**
 * Console Wallet adapter configuration
 */
interface ConsoleAdapterConfig {
  /**
   * Connection target mode.
   *
   * - 'local'    — Extension only. Fails if extension is not installed.
   * - 'remote'   — Mobile only. Shows QR code / deep link flow.
   * - 'combined' — (Default) Tries extension, falls back to QR/deep link.
   */
  target?: ConsoleConnectionTarget;
}
/**
 * Console Wallet adapter
 *
 * Implements WalletAdapter interface for Console Wallet using the official
 * dApp SDK. Supports browser extension (local), mobile QR/deep link (remote),
 * and auto-detection (combined) connection modes.
 *
 * The SDK handles transport internally:
 * - Local: window.postMessage to Chrome extension
 * - Remote: HTTP relay via consolewallet.io with QR code / deep link
 * - Combined: tries extension first, shows connector choice if unavailable
 */
declare class ConsoleAdapter implements WalletAdapter {
  readonly walletId: _partylayer_core.WalletId;
  readonly name = 'Console Wallet';
  private readonly target;
  /**
   * Tracks which transport was actually used for the current connection.
   * Set during connect(), cleared on disconnect().
   * - 'injected' — connected via browser extension
   * - 'remote'   — connected via relay (QR/deep link)
   * - null       — not connected
   */
  private activeTransport;
  constructor(config?: ConsoleAdapterConfig);
  getCapabilities(): CapabilityKey[];
  /**
   * Detect if Console Wallet is available.
   *
   * - local:    checks for browser extension via postMessage
   * - remote:   always available (SDK provides QR/deep link flow)
   * - combined: always available (extension preferred, mobile fallback)
   */
  detectInstalled(): Promise<AdapterDetectResult>;
  /**
   * Connect to Console Wallet.
   *
   * Passes the configured target to the SDK which handles transport selection:
   * - local: opens extension popup for user approval
   * - remote: shows QR code modal for mobile wallet scanning
   * - combined: tries extension, shows connector choice if unavailable
   */
  connect(
    ctx: AdapterContext,
    _opts?: {
      timeoutMs?: number;
      partyId?: PartyId;
      preferInstalled?: boolean;
    }
  ): Promise<AdapterConnectResult>;
  /**
   * Disconnect from Console Wallet.
   *
   * The SDK's disconnect() handles cleanup for both local and remote sessions,
   * including clearing any persisted relay session from IndexedDB.
   */
  disconnect(ctx: AdapterContext, session: Session): Promise<void>;
  /**
   * Restore session — verify wallet is still connected.
   *
   * For local mode: checks extension availability and connection status.
   * For remote/combined mode: checks connection status via isConnected(),
   * which internally checks both extension and persisted relay sessions.
   */
  restore(ctx: AdapterContext, persisted: PersistedSession): Promise<Session | null>;
  /**
   * Sign a message. Converts plain text to hex for the SDK.
   *
   * Works identically for both local and remote transports — the SDK routes
   * the request to the correct transport internally.
   */
  signMessage(
    ctx: AdapterContext,
    session: Session,
    params: SignMessageParams
  ): Promise<SignedMessage>;
  /**
   * Sign a transaction. Uses submitCommands without waitForFinalization.
   */
  signTransaction(
    ctx: AdapterContext,
    session: Session,
    params: SignTransactionParams
  ): Promise<SignedTransaction>;
  /**
   * Submit a transaction. Uses submitCommands with waitForFinalization.
   */
  submitTransaction(
    ctx: AdapterContext,
    session: Session,
    params: SubmitTransactionParams
  ): Promise<TxReceipt>;
  /**
   * Proxy a Ledger API request through the Console Wallet.
   *
   * Console Wallet is CIP-0103 compliant and exposes ledgerApi via its SDK.
   * Works through both local and remote transports.
   */
  ledgerApi(
    ctx: AdapterContext,
    session: Session,
    params: LedgerApiParams
  ): Promise<LedgerApiResult>;
  /**
   * Subscribe to wallet events.
   *
   * The SDK's event callbacks work for both local and remote transports.
   */
  on(
    event: 'connect' | 'disconnect' | 'sessionExpired' | 'txStatus' | 'error',
    handler: (payload: unknown) => void
  ): () => void;
  /**
   * Check extension availability via the SDK's postMessage probe.
   */
  private detectExtension;
}

export { ConsoleAdapter, type ConsoleAdapterConfig, type ConsoleConnectionTarget };
