// API SURFACE SNAPSHOT — @partylayer/react
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
import * as react_jsx_runtime from 'react/jsx-runtime';
import * as _partylayer_sdk from '@partylayer/sdk';
import {
  PartyLayerClient,
  Session,
  WalletInfo,
  ConnectOptions,
  LedgerApiParams,
  LedgerApiResult,
  RegistryStatus,
  SignMessageParams,
  SignedMessage,
  SignTransactionParams,
  SignedTransaction,
  SubmitTransactionParams,
  TxReceipt,
  WalletAdapter,
  AdapterClass,
  WalletId,
  CIP0103Provider,
  CapabilityKey,
  AdapterDetectResult,
  AdapterContext,
  PartyId,
  AdapterConnectResult,
  DiscoveredProvider,
  Cip0103StatusForDetection,
} from '@partylayer/sdk';
import {
  SessionStoreOptions,
  SessionStore,
  SessionAccount,
  SessionStatus,
  SessionState,
  SessionEvent,
  SessionStorage,
} from '@partylayer/session';
import * as _partylayer_core from '@partylayer/core';
export { RegistryStatus } from '@partylayer/registry-client';

interface PartyLayerContextValue {
  client: PartyLayerClient | null;
  session: Session | null;
  wallets: WalletInfo[];
  isLoading: boolean;
  error: Error | null;
  /**
   * Shared framework-agnostic session store (Step 6b). Backed by the client's
   * CIP-0103 provider and a localStorage adapter. Read by `useAccount` /
   * `useAccountEffect`. Additive — existing consumers can ignore it; the
   * legacy `session` field above is unchanged.
   */
  store: SessionStore | null;
}
declare function usePartyLayerContext(): PartyLayerContextValue;
interface PartyLayerProviderProps {
  client: PartyLayerClient;
  children: React.ReactNode;
  /** Network identifier (kept for backward compat; no longer used for native synthesis). */
  network?: string;
  /**
   * session-store options merged into the shared store
   * (`reconnect`, `expiry`, `broadcast`, `persistSnapshot`, `onInvalidate`,
   * `storage`). Omitted ⇒ today's default (localStorage marker, no
   * reconnect/broadcast). A provided `storage` overrides the default.
   */
  sessionOptions?: Partial<SessionStoreOptions>;
}
declare function PartyLayerProvider({
  client,
  children,
  sessionOptions,
}: PartyLayerProviderProps): react_jsx_runtime.JSX.Element;

/**
 * Hook to access PartyLayer client
 */
declare function usePartyLayer(): _partylayer_sdk.CantonConnectClient;
/**
 * Hook to get available wallets
 */
declare function useWallets(): {
  wallets: _partylayer_core.WalletInfo[];
  isLoading: boolean;
  error: Error | null;
};
/**
 * Hook to get the active SDK-layer session object.
 *
 * @deprecated Renamed from `useSession`. `useSession()` is now the reactive
 * session-store hook (`UseSessionReturn`); this legacy SDK-layer getter is
 * preserved VERBATIM under `useClientSession()`.
 * Migrate `useSession()` → `useClientSession()` if you want the old getter.
 */
declare function useClientSession(): Session | null;
/**
 * Hook to get registry status
 */
declare function useRegistryStatus(): {
  status: RegistryStatus | null;
  refresh: () => Promise<void>;
};
/**
 * Hook to connect to a wallet
 */
declare function useConnect(): {
  connect: (options?: ConnectOptions) => Promise<Session | null>;
  isConnecting: boolean;
  error: Error | null;
  reset: () => void;
};
/**
 * Hook to disconnect from a wallet
 */
declare function useDisconnect(): {
  disconnect: () => Promise<void>;
  isDisconnecting: boolean;
  error: Error | null;
};
/**
 * Hook to sign a message
 */
declare function useSignMessage(): {
  signMessage: (params: SignMessageParams) => Promise<SignedMessage | null>;
  isSigning: boolean;
  error: Error | null;
};
/**
 * Hook to sign a transaction
 */
declare function useSignTransaction(): {
  signTransaction: (params: SignTransactionParams) => Promise<SignedTransaction | null>;
  isSigning: boolean;
  error: Error | null;
};
/**
 * Hook to submit a transaction
 */
declare function useSubmitTransaction(): {
  submitTransaction: (params: SubmitTransactionParams) => Promise<TxReceipt | null>;
  isSubmitting: boolean;
  error: Error | null;
};
/**
 * Hook to call the Ledger API through the connected wallet
 */
declare function useLedgerApi(): {
  ledgerApi: (params: LedgerApiParams) => Promise<LedgerApiResult | null>;
  isLoading: boolean;
  error: Error | null;
};

/**
 * Lightweight theme system for PartyLayer UI components.
 * No external CSS-in-JS dependency — just a token object + React context.
 */
interface PartyLayerTheme {
  mode: 'light' | 'dark';
  colors: {
    primary: string;
    primaryHover: string;
    background: string;
    surface: string;
    text: string;
    textSecondary: string;
    border: string;
    success: string;
    successBg: string;
    error: string;
    errorBg: string;
    warning: string;
    warningBg: string;
    overlay: string;
  };
  borderRadius: string;
  fontFamily: string;
}
declare const lightTheme: PartyLayerTheme;
declare const darkTheme: PartyLayerTheme;
/**
 * Access the current PartyLayer theme.
 * Falls back to lightTheme if no ThemeProvider is present (backward-compatible).
 */
declare function useTheme(): PartyLayerTheme;
interface ThemeProviderProps {
  theme: 'light' | 'dark' | 'auto' | PartyLayerTheme;
  children: React.ReactNode;
}
declare function ThemeProvider({
  theme,
  children,
}: ThemeProviderProps): react_jsx_runtime.JSX.Element;

/** Map of walletId → icon URL for custom wallet logos */
type WalletIconMap = Record<string, string>;
/** Access wallet icon overrides from PartyLayerKit */
declare function useWalletIcons(): WalletIconMap;
/**
 * Resolve icon URL for a wallet. Priority:
 * 1. walletIcons map (exact match or fuzzy)
 * 2. wallet.icons.sm from registry
 * 3. null (caller renders fallback)
 */
declare function resolveWalletIcon(
  walletId: string,
  walletIcons: WalletIconMap,
  registryIconUrl?: string
): string | null;
interface PartyLayerKitProps {
  /** Canton network to connect to */
  network: 'devnet' | 'testnet' | 'mainnet';
  /** Application name shown to wallets during connection */
  appName: string;
  children: React.ReactNode;
  /** Registry URL override (default: https://registry.partylayer.xyz) */
  registryUrl?: string;
  /** Registry channel (default: 'stable') */
  channel?: 'stable' | 'beta';
  /**
   * Custom wallet adapters. If not provided, uses built-in adapters:
   * Console Wallet, 5N Loop, Cantor8.
   *
   * For Bron (enterprise OAuth), pass explicitly:
   *   adapters={[...getBuiltinAdapters(), new BronAdapter(config)]}
   */
  adapters?: (WalletAdapter | AdapterClass)[];
  /** Theme preset or custom theme object (default: 'light') */
  theme?: 'light' | 'dark' | 'auto' | PartyLayerTheme;
  /** Custom wallet icon URLs by walletId */
  walletIcons?: WalletIconMap;
  /**
   * Wallet ids in display order for the connect modal; wallets not listed fall
   * to the end. Sorts within the CIP-0103 Native / Available sections.
   */
  walletOrder?: readonly string[];
  /**
   * session-store options forwarded to `PartyLayerProvider`
   * (`reconnect`, `expiry`, `broadcast`, `persistSnapshot`, `storage`,
   * `onInvalidate`). Lets the app opt into encrypted persistence, auto-reconnect,
   * and multi-tab sync. Omitted ⇒ today's defaults.
   */
  sessionOptions?: Partial<SessionStoreOptions>;
}
declare function PartyLayerKit({
  network,
  appName,
  children,
  registryUrl,
  channel,
  adapters,
  theme,
  walletIcons,
  walletOrder,
  sessionOptions,
}: PartyLayerKitProps): react_jsx_runtime.JSX.Element;

interface WalletModalProps {
  isOpen: boolean;
  onClose: () => void;
  /**
   * Optional callback fired with the new session id once a wallet connects.
   * The modal already self-closes via `onClose` on success, and the session is
   * observable via hooks (`useSession`/`useAccount`), so wiring this is only
   * needed if you want the session id directly at connect time.
   */
  onConnect?: (sessionId: string) => void;
  /** Custom wallet icon URLs (merged with PartyLayerKit context) */
  walletIcons?: WalletIconMap;
  /**
   * Wallet ids in display order; wallets not listed fall to the end. Sorts
   * within the CIP-0103 Native / Available sections, preserving the section
   * structure. When omitted, the discovered order is preserved (default).
   */
  walletOrder?: readonly string[];
}
declare function WalletModal({
  isOpen,
  onClose,
  onConnect,
  walletIcons: propIcons,
  walletOrder: propWalletOrder,
}: WalletModalProps): react_jsx_runtime.JSX.Element | null;

/**
 * ConnectButton — Premium wallet connection button for Canton dApps.
 *
 * Manages the full lifecycle: disconnect → connect (via WalletModal) → connected state.
 * Uses existing hooks (useSession, useConnect, useDisconnect) under the hood.
 *
 * Designed for dApp developers to embed directly — brand-aligned, accessible,
 * and polished across light/dark themes.
 */
interface ConnectButtonProps {
  /** Button label when disconnected (default: "Connect Wallet") */
  label?: string;
  /** What to show when connected: partyId address, wallet name, or custom */
  connectedLabel?: 'address' | 'wallet' | 'custom';
  /** Custom formatter for connected display (requires connectedLabel='custom') */
  formatAddress?: (partyId: string) => string;
  /** Additional CSS class name */
  className?: string;
  /** Additional inline styles */
  style?: React.CSSProperties;
  /** Show disconnect option in dropdown (default: true) */
  showDisconnect?: boolean;
}
/**
 * Truncate a partyId for display: "party-abc123def456" → "party-abc...456"
 */
declare function truncatePartyId(id: string, chars?: number): string;
declare function ConnectButton({
  label,
  connectedLabel,
  formatAddress,
  className,
  style,
  showDisconnect,
}: ConnectButtonProps): react_jsx_runtime.JSX.Element;

/**
 * Native CIP-0103 Adapter
 *
 * Wraps a discovered CIP-0103 Provider into the PartyLayer WalletAdapter
 * interface. Used when a provider injected at `window.canton.*` does NOT
 * match any registry entry — i.e. an unknown CIP-0103 wallet that the
 * picker should still surface (with generic branding) so the user can
 * connect.
 *
 * For *known* CIP-0103 wallets — entries in the registry whose
 * `providerDetection` matches the active provider — we DO NOT create a
 * synthetic adapter. The registry's own adapter (e.g. `SendAdapter`) is
 * already registered via `getBuiltinAdapters()` and carries wallet-
 * specific behaviour (kernel.id guard, template-id hint, error mapping).
 * The picker promotes the registry's WalletInfo into the "CIP-0103
 * Native" section instead — see `context.tsx` for the merge logic.
 */

/**
 * A `DiscoveredProvider` augmented with the runtime `status` we fetched
 * during enrichment, plus an optional reference to the registry entry
 * whose `providerDetection` rules matched it.
 *
 * `matchedWallet` undefined → unknown CIP-0103 wallet (render generic).
 * `matchedWallet` set       → known wallet (registry entry handles the
 *                             rendering + connect flow; no synthetic).
 */
interface EnrichedProvider extends DiscoveredProvider {
  status?: Cip0103StatusForDetection;
  matchedWallet?: WalletInfo;
}
/**
 * A WalletAdapter that delegates to a native CIP-0103 Provider.
 * Used only for unknown CIP-0103 wallets — see file header.
 */
declare class NativeCIP0103Adapter implements WalletAdapter {
  readonly walletId: WalletId;
  readonly name: string;
  private provider;
  constructor(id: string, name: string, provider: CIP0103Provider);
  getCapabilities(): CapabilityKey[];
  detectInstalled(): Promise<AdapterDetectResult>;
  connect(
    _ctx: AdapterContext,
    _opts?: {
      timeoutMs?: number;
      partyId?: PartyId;
    }
  ): Promise<AdapterConnectResult>;
  disconnect(_ctx: AdapterContext, _session: Session): Promise<void>;
  signMessage(
    _ctx: AdapterContext,
    _session: Session,
    params: SignMessageParams
  ): Promise<SignedMessage>;
  signTransaction(
    _ctx: AdapterContext,
    _session: Session,
    params: SignTransactionParams
  ): Promise<SignedTransaction>;
  submitTransaction(
    _ctx: AdapterContext,
    _session: Session,
    params: SubmitTransactionParams
  ): Promise<TxReceipt>;
}
/**
 * Create a WalletAdapter from a discovered CIP-0103 provider.
 */
declare function createNativeAdapter(discovered: DiscoveredProvider): NativeCIP0103Adapter;
/**
 * Create a synthetic WalletInfo for an unknown CIP-0103 provider — i.e.
 * one whose runtime status did NOT match any registry entry. The picker
 * still surfaces it (decision: "show all wallets"), with a name derived
 * from `kernel.userUrl` and a generic Canton-themed icon.
 *
 * For known wallets (registry-matched), don't call this — promote the
 * registry's WalletInfo to native instead. See `promoteRegistryToNative`.
 */
declare function createSyntheticWalletInfo(
  discovered: EnrichedProvider,
  network: string
): WalletInfo;

/**
 * React hooks over the @partylayer/session core (Step 6b).
 *
 * NEW, additive hooks — `useAccount` and `useAccountEffect` — with wagmi
 * parity. They read the shared `SessionStore` created by `PartyLayerProvider`
 * via `useSyncExternalStore`. The existing `useSession` (SDK-layer) is left
 * untouched; the two coexist until the M2 react v2 unification.
 */

/** wagmi-parity-ish chain handle derived from the CAIP-2 networkId. */
interface SessionChain {
  /** CAIP-2 network id, e.g. "canton:da-mainnet". */
  id: string;
}
interface UseAccountReturn {
  /** Active party id (Canton's address analog), or null. */
  party: string | null;
  /** wagmi-parity alias of `party`. */
  address: string | null;
  /** Full active (primary) account, or null. */
  account: SessionAccount | null;
  /** All accounts the wallet exposed. */
  accounts: readonly SessionAccount[];
  /** Connection status state-machine value. */
  status: SessionStatus;
  isConnected: boolean;
  isConnecting: boolean;
  isReconnecting: boolean;
  isDisconnected: boolean;
  /** Active network in CAIP-2 form, or null. */
  networkId: string | null;
  /** wagmi-parity chain handle derived from `networkId`, or null. */
  chain: SessionChain | null;
  /** Last connect/restore error, or null. */
  lastError: Error | null;
}
/**
 * Read the active account/connection from the shared session store.
 *
 * wagmi parity: `useAccount()` returns `{ address, status, isConnected, ... }`.
 * SSR-safe — `getServerSnapshot` returns a stable disconnected snapshot.
 */
declare function useAccount(): UseAccountReturn;
/**
 * Reactive session: the full `SessionState` (live, via `useSyncExternalStore`)
 * plus the store's actions and the resilience/sync event subscription.
 *
 * NOTE — this is the NEW meaning of `useSession()`. The previous SDK-layer
 * getter (`return context.session`) is preserved VERBATIM as `useClientSession()`.
 * Migration: `useSession()` (old) → `useClientSession()`.
 *
 * SSR-safe: with no store (server / outside provider) it returns the stable
 * disconnected snapshot and no-op actions; no `window`/BroadcastChannel access.
 */
interface UseSessionReturn extends SessionState {
  isConnected: boolean;
  isConnecting: boolean;
  isReconnecting: boolean;
  isDisconnected: boolean;
  /** Connect via the store (CIP-0103 `connect`). */
  connect(params?: Record<string, unknown>): Promise<SessionState>;
  /** Disconnect via the store (never auto-reconnects after). */
  disconnect(): Promise<void>;
  /** Restore/rehydrate from the live provider + persisted marker/snapshot. */
  restore(): Promise<SessionState>;
  /** Subscribe to a structured resilience/sync event (narrowed by `event`). */
  on<T extends SessionEvent['type']>(
    event: T,
    handler: (
      event: Extract<
        SessionEvent,
        {
          type: T;
        }
      >
    ) => void
  ): () => void;
}
declare function useSession(): UseSessionReturn;
interface UseAccountEffectParameters {
  /** Fired on a transition INTO `connected` (from disconnected/connecting/reconnecting). */
  onConnect?: (data: {
    account: SessionAccount | null;
    accounts: readonly SessionAccount[];
    networkId: string | null;
  }) => void;
  /** Fired on a transition `connected → disconnected`. */
  onDisconnect?: () => void;
  /**
   * fired when the active PRIMARY party changes (the session
   * `party:changed` event — a true switch, not a list reorder).
   */
  onPartyChanged?: (data: { previous: string | null; current: string | null }) => void;
}
/**
 * Fire side-effects on session status transitions — no render churn.
 *
 * - `onConnect` runs once when status becomes `connected`.
 * - `onDisconnect` runs once on `connected → disconnected`.
 */
declare function useAccountEffect(parameters?: UseAccountEffectParameters): void;

/**
 * Browser `localStorage`-backed `SessionStorage` for the session core.
 *
 * The `@partylayer/session` core is DOM-free and never touches `localStorage`
 * itself — this adapter is the only place that does, and it is SSR-safe
 * (guards `typeof window`). The `PartyLayerProvider` injects it into the
 * session store it creates.
 */

/**
 * Create a `SessionStorage` backed by `window.localStorage`. On the server (or
 * any environment without `localStorage`) every method is a safe no-op, so the
 * session core degrades to "no persistence" rather than throwing.
 */
declare function createLocalStorage(): SessionStorage;

export {
  PartyLayerProvider as CantonConnectProvider,
  ConnectButton,
  type ConnectButtonProps,
  NativeCIP0103Adapter,
  PartyLayerKit,
  type PartyLayerKitProps,
  PartyLayerProvider,
  type PartyLayerTheme,
  type SessionChain,
  ThemeProvider,
  type UseAccountEffectParameters,
  type UseAccountReturn,
  type UseSessionReturn,
  type WalletIconMap,
  WalletModal,
  type WalletModalProps,
  createLocalStorage,
  createNativeAdapter,
  createSyntheticWalletInfo,
  darkTheme,
  lightTheme,
  resolveWalletIcon,
  truncatePartyId,
  useAccount,
  useAccountEffect,
  usePartyLayer as useCantonConnect,
  useClientSession,
  useConnect,
  useDisconnect,
  useLedgerApi,
  usePartyLayer,
  usePartyLayerContext,
  useRegistryStatus,
  useSession,
  useSignMessage,
  useSignTransaction,
  useSubmitTransaction,
  useTheme,
  useWalletIcons,
  useWallets,
};
