// API SURFACE SNAPSHOT — @partylayer/testing
// Generated by scripts/gate/api-snapshot.mjs from the package's published
// "types" entry point, normalized through Prettier. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
export {
  M as MOCK_SCENARIO_NAMES,
  a as MockMethod,
  b as MockScenario,
  c as MockScenarioName,
  d as MockWalletClient,
  e as MockWalletConfig,
  O as OfflineHarness,
  T as TxEventRecorder,
  f as connectMock,
  g as createMockWallet,
  h as createMockWalletClient,
  i as createOfflineHarness,
  r as recordTxEvents,
  s as scenarioToError,
} from './offline-CELeTEq9.js';
import { CIP0103Provider, CIP0103TxChangedEvent } from '@partylayer/core';
import {
  ChannelFactory,
  SessionStore,
  SessionState,
  ExpiryOptions,
  RetryPolicy,
} from '@partylayer/session';
import '@partylayer/provider';

/**
 * Simulated, controllable transaction lifecycle.
 *
 * Exposes the session-layer view (boolean phase flags
 * isPreparing → isSubmitting → isConfirming → isFinalized, plus a `failed`
 * terminal) AND emits the SAME CIP-0103 `txChanged` events the real provider
 * emits, so tests can assert against either view.
 *
 * Two drive modes:
 *   - manual: `advance()` steps one phase at a time; `fail()` terminates.
 *   - auto:   `start()` walks all phases using configurable per-phase delays
 *             (uses setTimeout — fake-timer friendly).
 *
 * Phase → CIP-0103 `txChanged.status` mapping:
 *   preparing  → 'pending'
 *   submitting → 'signed'   (payload: { signature, signedBy, party })
 *   confirming → (no CIP-0103 status — see note)
 *   finalized  → 'executed' (payload: { updateId, completionOffset })
 *   failed     → 'failed'
 *
 * NOTE — 'confirming' has no CIP-0103 `txChanged` status: the spec's tx union
 * goes signed → executed with no intermediate "confirming" state. We still
 * model `isConfirming` as the post-signed waiting window because the session
 * layer surfaces it as a UI flag. The session-lifecycle harness
 * (`createSessionHarness`) and the TanStack Query utilities
 * (`@partylayer/testing/query`) build on top of this controller.
 */

type LifecyclePhase = 'idle' | 'preparing' | 'submitting' | 'confirming' | 'finalized' | 'failed';
type LifecycleDelays = Partial<
  Record<'preparing' | 'submitting' | 'confirming' | 'finalized', number>
>;
interface LifecycleConfig {
  /** Command id stamped on every emitted event. */
  commandId?: string;
  /** Party id used in the 'signed' payload. */
  party?: string;
  /** Signature used in the 'signed' payload. */
  signature?: string;
  /** Update id used in the 'executed' payload. */
  updateId?: string;
  /**
   * Optional provider to ALSO emit `txChanged` onto (in addition to this
   * controller's own listeners), so events surface on a mock wallet's bus.
   */
  provider?: CIP0103Provider;
  /** Per-phase delays for auto mode (`start()`). Default 0. */
  delays?: LifecycleDelays;
}
interface TransactionLifecycle {
  readonly commandId: string;
  readonly phase: LifecyclePhase;
  readonly isPreparing: boolean;
  readonly isSubmitting: boolean;
  readonly isConfirming: boolean;
  readonly isFinalized: boolean;
  readonly isFailed: boolean;
  /** Subscribe to `txChanged`. Returns an unsubscribe function. */
  on(event: string, listener: (event: CIP0103TxChangedEvent) => void): () => void;
  /** Manual step to the next phase; emits the mapped event. Returns the new phase. */
  advance(): LifecyclePhase;
  /** Terminal failure: emits `txChanged` `{ status: 'failed' }`. */
  fail(): void;
  /** Auto mode: walk every phase with configured delays. Resolves at 'finalized'. */
  start(): Promise<void>;
  /** Reset back to 'idle' (does not emit). */
  reset(): void;
}
declare function createTransactionLifecycle(config?: LifecycleConfig): TransactionLifecycle;

/**
 * Session-lifecycle simulation harness.
 *
 * Drives a REAL `@partylayer/session` store through a controllable CIP-0103
 * provider, so every scenario exercises the store's own machinery — not
 * synthetic shortcuts:
 *   - `expire()`            advances the store's REAL expiry timer (the
 *                           `session:expired` / `onReauthRequired` path); it never
 *                           emits a fake `session:expired`. Requires fake-timer
 *                           control via `advanceTimers` (the store arms expiry
 *                           with `setTimeout`).
 *   - `dropConnection()` /  emit the provider's real `statusChanged` CIP-0103
 *     `restoreConnection()` event — the same signal a live wallet sends — driving
 *                           the store's transient-disconnect / reconnect path.
 *   - `switchParty()`       emits a real `accountsChanged` with a new primary,
 *                           driving the store's `party:changed` detection.
 *   - `openTab()`           returns a second harness whose store shares this
 *                           harness's in-memory BroadcastChannel hub, so a
 *                           disconnect in one tab propagates to the other.
 *
 * Lifecycle: each harness OWNS its own store; `destroy()` is per-harness (a
 * child from `openTab()` must be destroyed by the caller — it is not torn down
 * with its parent).
 */

interface SessionHarnessConfig {
  /** Initial primary party id. Default `party::harness-1`. */
  partyId?: string;
  /** CAIP-2 network id reported by the provider. Default `canton:da-devnet`. */
  networkId?: string;
  /** Expiry TTL (ms) armed on connect. Default `60_000`. Drive it with `expire()`. */
  ttlMs?: number;
  /** App re-auth hook invoked by the store's real expiry path. */
  onReauthRequired?: ExpiryOptions['onReauthRequired'];
  /** Reconnect policy passed straight to the store (default: store default). */
  reconnect?: RetryPolicy | false;
  /**
   * Advance timers to fire the store's REAL `setTimeout`-based expiry/backoff —
   * e.g. `vi.advanceTimersByTimeAsync`. Required for `expire()` and for
   * deterministic reconnect timing. Omit only if you don't call `expire()`.
   */
  advanceTimers?: (ms: number) => void | Promise<void>;
  /** @internal shared multi-tab hub (set by `openTab`). */
  _hub?: ChannelHub;
}
interface SessionHarness {
  /** The live session store under test. */
  readonly store: SessionStore;
  /** The controllable CIP-0103 provider backing the store. */
  readonly provider: CIP0103Provider;
  /** Connect via the real store flow (arms the expiry timer). */
  connect(): Promise<SessionState>;
  /** Fire a real transient `statusChanged(false)` (NOT an explicit disconnect). */
  dropConnection(): void;
  /** Fire a real `statusChanged(true)` to restore the connection. */
  restoreConnection(): void;
  /** Fire a real `accountsChanged` with a new primary → `party:changed`. */
  switchParty(partyId: string): void;
  /** Advance the store's REAL expiry timer past its TTL (no synthetic emit). */
  expire(): Promise<void>;
  /** A second harness sharing this one's broadcast hub (simulates another tab). */
  openTab(config?: Omit<SessionHarnessConfig, '_hub'>): SessionHarness;
  /** Tear down THIS harness's store/provider (per-harness; children are separate). */
  destroy(): void;
}
/** A synchronous in-memory BroadcastChannel hub shared across tabs. */
interface ChannelHub {
  factory: ChannelFactory;
}
/** Build a hub whose channels deliver to OTHER instances only (no echo to sender). */
declare function createChannelHub(): ChannelHub;
declare function createSessionHarness(config?: SessionHarnessConfig): SessionHarness;

/**
 * Reusable browser-test primitives for a real-browser (Playwright) smoke —
 * framework-agnostic: every helper returns a STRING of JS to run via
 * `page.addInitScript(...)` / `page.evaluate(...)`, so this package takes NO
 * dependency on Playwright. The actual smoke lives in `apps/demo/e2e`.
 */
interface MockWalletInjectionOptions {
  /** Key on `window.canton` the wallet registers under. Default `mock`. */
  walletId?: string;
  /** Primary party id the mock reports. Default `party::e2e-1`. */
  partyId?: string;
  /** CAIP-2 network id. Default `canton:da-devnet`. */
  networkId?: string;
}
/**
 * An init script that installs a minimal CIP-0103-shaped provider at
 * `window.canton[walletId]` BEFORE the app loads, so a real-browser test can
 * drive the connect flow with no extension/live wallet. Inject via
 * `page.addInitScript({ content: mockWalletInjectionScript() })`.
 */
declare function mockWalletInjectionScript(options?: MockWalletInjectionOptions): string;
/**
 * A script returning the number of object stores' total entries for an IndexedDB
 * database (or -1 if the DB does not exist) — used to assert encrypted-session
 * persistence engaged after a connect. Run via `page.evaluate(idbEntryCountScript(db))`.
 */
declare function idbEntryCountScript(dbName: string): string;
/** The origin-bound IndexedDB name the session key store uses for a given origin. */
declare function sessionKeyDbName(origin: string): string;

export {
  type ChannelHub,
  type LifecycleConfig,
  type LifecycleDelays,
  type LifecyclePhase,
  type MockWalletInjectionOptions,
  type SessionHarness,
  type SessionHarnessConfig,
  type TransactionLifecycle,
  createChannelHub,
  createSessionHarness,
  createTransactionLifecycle,
  idbEntryCountScript,
  mockWalletInjectionScript,
  sessionKeyDbName,
};
