// API SURFACE SNAPSHOT — @partylayer/react-native
// AST-normalized: strip comments → reprint each top-level declaration →
// collapse whitespace → sort. Immune to comments / formatting / declaration
// order; still flags any real type change (symbols, signatures, members
// including private). Order is NOT a public contract, so it is sorted away.
// Schema: ast-normalized-v1 · TypeScript 5.9.3
// Generated by scripts/gate/api-snapshot.mjs. DO NOT edit by hand.
// To intentionally accept a public-API change, run: pnpm gate:api:update
// ----------------------------------------------------------------------------
declare function PartyLayerProvider({ client, children, asyncStorage, sessionOptions, }: PartyLayerProviderProps): react_jsx_runtime.JSX.Element;
declare function ThemeProvider({ theme, children }: ThemeProviderProps): react_jsx_runtime.JSX.Element;
declare function createAsyncStorage(asyncStorage: RNAsyncStorage): SessionStorage;
declare function createAsyncStorageAdapter(asyncStorage: RNAsyncStorage): StorageAdapter;
declare function createReactNativeClient(config: ReactNativeClientConfig): PartyLayerClient;
declare function createReactNativeDeepLinkPlatform(linking?: RNLinking): DeepLinkPlatform;
declare function useAccount(): UseAccountResult;
declare function useAccountEffect(parameters?: UseAccountEffectParameters): void;
declare function useConnect(): UseConnectResult;
declare function useConnect(client: PartyLayerClient): UseConnectResult;
declare function useDisconnect(): UseDisconnectResult;
declare function useDisconnect(client: PartyLayerClient): UseDisconnectResult;
declare function useLedgerApi(): UseLedgerApiResult;
declare function useLedgerApi(client: PartyLayerClient): UseLedgerApiResult;
declare function usePartyLayer(): PartyLayerClient;
declare function usePartyLayerContext(): PartyLayerContextValue;
declare function useSession(): UseSessionResult;
declare function useSignMessage(): UseSignMessageResult;
declare function useSignMessage(client: PartyLayerClient): UseSignMessageResult;
declare function useSignTransaction(): UseSignTransactionResult;
declare function useSignTransaction(client: PartyLayerClient): UseSignTransactionResult;
declare function useSubmitTransaction(): UseSubmitTransactionResult;
declare function useSubmitTransaction(client: PartyLayerClient): UseSubmitTransactionResult;
declare function useTheme(): ReactNativeTheme;
declare function useWallets(): UseWalletsResult;
declare function useWallets(client: PartyLayerClient, parameters?: UseWalletsParameters): UseWalletsResult;
declare function useWallets(parameters: UseWalletsParameters): UseWalletsResult;
export { A as AccentOverrides, a as AccentPreset, D as DEFAULT_BORDER_RADIUS, I as IconFormat, b as REM_BASE_PX, T as ThemeFamily, c as accentPresets, d as applyAccent, e as deriveIconFormat, p as parseBorderRadius, t as themes, f as toReactNativeTheme, g as toThemeTokens, w as walletIconInfo } from './icons-aZXHJrwj.js';
export { type ConnectStatus, type DynamicReactNativeTheme, type PartyLayerContextValue, PartyLayerProvider, type PartyLayerProviderProps, PartyLayerTheme, type RNAsyncStorage, type RNLinking, type ReactNativeClientConfig, ReactNativeTheme, type ReactNativeThemeInput, type SessionChain, ThemeProvider, type ThemeProviderProps, type UseAccountEffectParameters, type UseAccountResult, type UseConnectResult, type UseDisconnectResult, type UseLedgerApiResult, type UseSessionResult, type UseSignMessageResult, type UseSignTransactionResult, type UseSubmitTransactionResult, type UseWalletsParameters, type UseWalletsResult, WalletIconInfo, createAsyncStorage, createAsyncStorageAdapter, createReactNativeClient, createReactNativeDeepLinkPlatform, useAccount, useAccountEffect, useConnect, useDisconnect, useLedgerApi, usePartyLayer, usePartyLayerContext, useSession, useSignMessage, useSignTransaction, useSubmitTransaction, useTheme, useWallets };
import * as react_jsx_runtime from 'react/jsx-runtime';
import { DeepLinkPlatform, StorageAdapter } from '@partylayer/core';
import { PartyLayerClient, Session, WalletInfo, PartyLayerConfig, LedgerApiParams, LedgerApiResult, SignMessageParams, SignedMessage, SignTransactionParams, SignedTransaction, SubmitTransactionParams, TxReceipt, WalletFilter, ConnectOptions } from '@partylayer/sdk';
import { SessionStore, SessionStoreOptions, SessionStorage, SessionAccount, SessionStatus, SessionState, SessionEvent } from '@partylayer/session';
import { W as WalletIconInfo, R as ReactNativeTheme, P as PartyLayerTheme } from './icons-aZXHJrwj.js';
interface DynamicReactNativeTheme { lightMode: ReactNativeTheme | PartyLayerTheme; darkMode: ReactNativeTheme | PartyLayerTheme; }
interface PartyLayerContextValue { client: PartyLayerClient | null; session: Session | null; wallets: WalletInfo[]; isLoading: boolean; error: Error | null; store: SessionStore | null; }
interface PartyLayerProviderProps { client: PartyLayerClient; children: React.ReactNode; asyncStorage?: RNAsyncStorage; sessionOptions?: Partial<SessionStoreOptions>; }
interface RNAsyncStorage { getItem(key: string): Promise<string | null>; setItem(key: string, value: string): Promise<void>; removeItem(key: string): Promise<void>; clear(): Promise<void>; }
interface RNLinking { openURL(url: string): Promise<unknown>; addEventListener(type: 'url', handler: (event: { url: string; }) => void): { remove(): void; }; getInitialURL(): Promise<string | null>; }
interface ReactNativeClientConfig extends PartyLayerConfig { asyncStorage?: RNAsyncStorage; }
interface SessionChain { id: string; }
interface ThemeProviderProps { theme: ReactNativeThemeInput; children: React.ReactNode; }
interface UseAccountEffectParameters { onConnect?: (data: { account: SessionAccount | null; accounts: readonly SessionAccount[]; networkId: string | null; }) => void; onDisconnect?: () => void; onPartyChanged?: (data: { previous: string | null; current: string | null; }) => void; }
interface UseAccountResult { party: string | null; address: string | null; account: SessionAccount | null; accounts: readonly SessionAccount[]; status: SessionStatus; isConnected: boolean; isConnecting: boolean; isReconnecting: boolean; isDisconnected: boolean; networkId: string | null; chain: SessionChain | null; lastError: Error | null; }
interface UseConnectResult { connect: (options?: ConnectOptions) => Promise<Session>; disconnect: () => Promise<void>; session: Session | null; status: ConnectStatus; isConnecting: boolean; isConnected: boolean; error: Error | null; }
interface UseDisconnectResult { disconnect: () => Promise<void>; isDisconnecting: boolean; error: Error | null; }
interface UseLedgerApiResult { ledgerApi: (params: LedgerApiParams) => Promise<LedgerApiResult>; isLoading: boolean; error: Error | null; reset: () => void; }
interface UseSessionResult extends SessionState { isConnected: boolean; isConnecting: boolean; isReconnecting: boolean; isDisconnected: boolean; connect(params?: Record<string, unknown>): Promise<SessionState>; disconnect(): Promise<void>; restore(): Promise<SessionState>; on<T extends SessionEvent['type']>(event: T, handler: (event: Extract<SessionEvent, { type: T; }>) => void): () => void; }
interface UseSignMessageResult { signMessage: (params: SignMessageParams) => Promise<SignedMessage>; isSigning: boolean; error: Error | null; reset: () => void; }
interface UseSignTransactionResult { signTransaction: (params: SignTransactionParams) => Promise<SignedTransaction>; isSigning: boolean; error: Error | null; reset: () => void; }
interface UseSubmitTransactionResult { submitTransaction: (params: SubmitTransactionParams) => Promise<TxReceipt>; isSubmitting: boolean; error: Error | null; reset: () => void; }
interface UseWalletsParameters { filter?: WalletFilter; }
interface UseWalletsResult { wallets: WalletInfo[] | undefined; walletIcons: WalletIconInfo[]; isLoading: boolean; isSuccess: boolean; isError: boolean; error: Error | null; refetch: () => void; }
type ConnectStatus = 'idle' | 'connecting' | 'connected' | 'error';
type ReactNativeThemeInput = 'light' | 'dark' | 'auto' | PartyLayerTheme | ReactNativeTheme | DynamicReactNativeTheme;
