#!/usr/bin/env node
/**
 * gen-readme.mjs: single-source-of-truth wallet docs from the registry.
 *
 * Reads registry/v1/stable/registry.json and generates:
 *   1. A markdown wallet table, injected between WALLETS markers in:
 *        README.md, packages/sdk/README.md, packages/react/README.md
 *   2. A typed data module the docs wallet page imports (Table 1):
 *        apps/demo/src/app/docs/wallets/wallets.generated.ts
 *
 * Modes (mirrors scripts/gate/api-snapshot.mjs):
 *   node scripts/gen-readme.mjs           # --check: regenerate in memory, diff
 *                                          #   committed output, exit 1 on drift
 *   node scripts/gen-readme.mjs --write    # apply to disk
 *
 * gate:readme runs the check mode so the READMEs + docs wallet list can never
 * drift from the registry.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const WRITE = process.argv.includes('--write');

const START = '<!-- WALLETS:START (generated by scripts/gen-readme.mjs, do not edit) -->';
const END = '<!-- WALLETS:END -->';

const CAP_KEYS = [
  'signMessage',
  'signTransaction',
  'submitTransaction',
  'transactionStatus',
  'switchNetwork',
  'multiParty',
];

const registry = JSON.parse(
  readFileSync(join(ROOT, 'registry/v1/stable/registry.json'), 'utf-8'),
);
const wallets = registry.wallets;

const networks = (w) => (w.supportedNetworks ?? []).join(', ');
const optIn = (w) => (w.adapter?.requiresConfig ? 'Yes' : 'No');
const capabilities = (w) => {
  const on = CAP_KEYS.filter((k) => w.capabilities?.[k] === true);
  return on.length ? on.join(', ') : 'none';
};

/** The markdown table injected into the READMEs. */
function markdownTable() {
  const lines = [
    '| Wallet | Networks | Capabilities | Opt-in | Adapter |',
    '|--------|----------|--------------|--------|---------|',
    ...wallets.map(
      (w) => `| ${w.name} | ${networks(w)} | ${capabilities(w)} | ${optIn(w)} | \`${w.adapter?.type ?? ''}\` |`,
    ),
  ];
  return lines.join('\n');
}

/** The typed data module the docs wallet page (Table 1) imports. */
function dataModule() {
  const entries = wallets
    .map((w) => {
      const caps = CAP_KEYS.map((k) => `${k}: ${w.capabilities?.[k] === true}`).join(', ');
      const nets = (w.supportedNetworks ?? []).map((n) => `'${n}'`).join(', ');
      return (
        `  {\n` +
        `    id: '${w.id}',\n` +
        `    name: ${JSON.stringify(w.name)},\n` +
        `    networks: [${nets}],\n` +
        `    capabilities: { ${caps} },\n` +
        `    optIn: ${w.adapter?.requiresConfig === true},\n` +
        `    adapter: ${JSON.stringify(w.adapter?.type ?? '')},\n` +
        `  },`
      );
    })
    .join('\n');

  return `// GENERATED by scripts/gen-readme.mjs from registry/v1/stable/registry.json, do not edit.
// Run \`pnpm gen:readme\` to regenerate; \`pnpm gate:readme\` checks for drift.

export interface GeneratedWallet {
  id: string;
  name: string;
  networks: string[];
  capabilities: {
    signMessage: boolean;
    signTransaction: boolean;
    submitTransaction: boolean;
    transactionStatus: boolean;
    switchNetwork: boolean;
    multiParty: boolean;
  };
  /** True when the adapter is opt-in (requires explicit config/registration). */
  optIn: boolean;
  adapter: string;
}

export const GENERATED_WALLETS: GeneratedWallet[] = [
${entries}
];
`;
}

/** Replace the content between the WALLETS markers in a markdown file. */
function injectMarkers(relPath, table) {
  const file = join(ROOT, relPath);
  const src = readFileSync(file, 'utf-8');
  const startIdx = src.indexOf(START);
  const endIdx = src.indexOf(END);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`Missing WALLETS markers in ${relPath}, add ${START} ... ${END} first.`);
  }
  const before = src.slice(0, startIdx + START.length);
  const after = src.slice(endIdx);
  return { file, relPath, next: `${before}\n${table}\n${after}` };
}

// ── Compute all targets ──────────────────────────────────────────────────────
const table = markdownTable();
const targets = [
  injectMarkers('README.md', table),
  injectMarkers('packages/sdk/README.md', table),
  injectMarkers('packages/react/README.md', table),
];
const moduleRel = 'apps/demo/src/app/docs/wallets/wallets.generated.ts';
const moduleFile = join(ROOT, moduleRel);
const moduleNext = dataModule();
targets.push({ file: moduleFile, relPath: moduleRel, next: moduleNext });

// ── Apply or check ───────────────────────────────────────────────────────────
if (WRITE) {
  let wrote = 0;
  for (const t of targets) {
    const cur = (() => {
      try {
        return readFileSync(t.file, 'utf-8');
      } catch {
        return null;
      }
    })();
    if (cur !== t.next) {
      writeFileSync(t.file, t.next);
      wrote++;
      console.log(`  wrote ${t.relPath}`);
    }
  }
  console.log(`✓ gen:readme: ${wallets.length} wallets; ${wrote} file(s) updated.`);
  process.exit(0);
}

// check mode
const drifted = [];
for (const t of targets) {
  let cur = null;
  try {
    cur = readFileSync(t.file, 'utf-8');
  } catch {
    cur = null;
  }
  if (cur !== t.next) drifted.push(t.relPath);
}
if (drifted.length > 0) {
  console.error('✗ README/docs wallet data is out of sync with the registry:');
  for (const r of drifted) console.error(`    ${r}`);
  console.error('');
  console.error('  Run `pnpm gen:readme` to regenerate, then commit the result.');
  process.exit(1);
}
console.log(`✓ gate:readme: README + docs wallet data in sync with the registry (${wallets.length} wallets).`);
process.exit(0);
